package ikuaiapi

type V4Endpoint struct {
	Group   string
	Name    string
	Path    string
	Methods []string
}

var V4EndpointCatalog = []V4Endpoint{
	{Group: "advanced", Name: "ftp-config", Path: "/advanced-service/ftp-config", Methods: []string{"GET", "PUT"}},
	{Group: "advanced", Name: "ftp-users", Path: "/advanced-service/ftp-users", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "advanced", Name: "http-users", Path: "/advanced-service/http-users", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "advanced", Name: "samba-config", Path: "/advanced-service/samba-config", Methods: []string{"GET", "PUT"}},
	{Group: "advanced", Name: "samba-users", Path: "/advanced-service/samba-users", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "advanced", Name: "snmpd-config", Path: "/advanced-service/snmpd-config", Methods: []string{"GET", "PUT"}},
	{Group: "auth", Name: "online-users", Path: "/auth/online-users", Methods: []string{"GET", "DELETE"}},
	{Group: "auth", Name: "packages", Path: "/auth/packages", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "auth", Name: "users", Path: "/auth/users", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "auth", Name: "web-services", Path: "/auth/web/services", Methods: []string{"GET", "PUT"}},
	{Group: "interfaces", Name: "lan-config", Path: "/interfaces/lan-config", Methods: []string{"GET"}},
	{Group: "interfaces", Name: "physical", Path: "/interfaces/physical", Methods: []string{"GET"}},
	{Group: "interfaces", Name: "wan-config", Path: "/interfaces/wan-config", Methods: []string{"GET"}},
	{Group: "interfaces", Name: "wan-vlan-config", Path: "/interfaces/wan-vlan-config", Methods: []string{"GET"}},
	{Group: "log", Name: "arp", Path: "/log/arp", Methods: []string{"GET", "DELETE"}},
	{Group: "log", Name: "auth", Path: "/log/auth", Methods: []string{"GET", "DELETE"}},
	{Group: "log", Name: "ddns", Path: "/log/ddns", Methods: []string{"GET", "DELETE"}},
	{Group: "log", Name: "dhcp", Path: "/log/dhcp", Methods: []string{"GET", "DELETE"}},
	{Group: "log", Name: "notice", Path: "/log/notice", Methods: []string{"GET", "DELETE"}},
	{Group: "log", Name: "pppoe", Path: "/log/pppoe", Methods: []string{"GET", "DELETE"}},
	{Group: "log", Name: "system", Path: "/log/system", Methods: []string{"GET", "DELETE"}},
	{Group: "log", Name: "web-activity", Path: "/log/web_activity", Methods: []string{"GET", "DELETE"}},
	{Group: "log", Name: "wireless", Path: "/log/wireless", Methods: []string{"GET", "DELETE"}},
	{Group: "monitoring", Name: "app-protocols-history-load", Path: "/monitoring/app-protocols/history-load", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "app-protocols-load", Path: "/monitoring/app-protocols/load", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "app-protocols-terminal-load", Path: "/monitoring/app-protocols/terminal-load", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "app-traffic-summary", Path: "/monitoring/app-traffic-summary", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "cameras", Path: "/monitoring/cameras", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "channel-clients", Path: "/monitoring/channel-clients", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "clients-app-protocols-load", Path: "/monitoring/clients/app-protocols/load", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "clients-ip6-offline", Path: "/monitoring/clients-ip6-offline", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "clients-ip6-online", Path: "/monitoring/clients-ip6-online", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "clients-offline", Path: "/monitoring/clients-offline", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "clients-online", Path: "/monitoring/clients-online", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "clients-protocols", Path: "/monitoring/clients/protocols", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "clients-protocols-history-load", Path: "/monitoring/clients/protocols/history-load", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "clients-traffic-load", Path: "/monitoring/clients-traffic-load", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "clients-traffic-summary", Path: "/monitoring/clients-traffic-summary", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "connections", Path: "/monitoring/connections", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "cpu", Path: "/monitoring/cpu", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "cputemp", Path: "/monitoring/cputemp", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "disk", Path: "/monitoring/disk", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "downstream", Path: "/monitoring/downstream", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "flow-shunting", Path: "/monitoring/flow-shunting", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "interfaces-config", Path: "/monitoring/interfaces-config", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "interfaces-physical", Path: "/monitoring/interfaces-physical", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "interfaces-status", Path: "/monitoring/interfaces-status", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "interfaces-traffic", Path: "/monitoring/interfaces-traffic", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "interfaces-traffic-v6", Path: "/monitoring/interfaces-traffic-v6", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "memory", Path: "/monitoring/memory", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "network", Path: "/monitoring/network", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "protocols", Path: "/monitoring/protocols", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "protocols-history-load", Path: "/monitoring/protocols/history-load", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "ssid-clients", Path: "/monitoring/ssid-clients", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "switch", Path: "/monitoring/switch", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "system", Path: "/monitoring/system", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "terminals", Path: "/monitoring/terminals", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "wireless-score", Path: "/monitoring/wireless-score", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "wireless-statistics", Path: "/monitoring/wireless-statistics", Methods: []string{"GET"}},
	{Group: "monitoring", Name: "wireless-traffic", Path: "/monitoring/wireless-traffic", Methods: []string{"GET"}},
	{Group: "network", Name: "ac-ap-config", Path: "/network/ac/ap-config", Methods: []string{"GET", "PUT", "DELETE"}},
	{Group: "network", Name: "ac-services", Path: "/network/ac/services", Methods: []string{"GET", "PUT"}},
	{Group: "network", Name: "ac-services-start", Path: "/network/ac/services:start", Methods: []string{"POST"}},
	{Group: "network", Name: "ac-services-stop", Path: "/network/ac/services:stop", Methods: []string{"POST"}},
	{Group: "network", Name: "dhcp-access-control-mode", Path: "/network/dhcp/access-control/mode", Methods: []string{"GET", "PUT"}},
	{Group: "network", Name: "dhcp-access-control-rules", Path: "/network/dhcp/access-control/rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "network", Name: "dhcp-clients", Path: "/network/dhcp/clients", Methods: []string{"GET"}},
	{Group: "network", Name: "dhcp-services", Path: "/network/dhcp/services", Methods: []string{"GET", "POST", "PUT", "PATCH"}},
	{Group: "network", Name: "dhcp-services-restart", Path: "/network/dhcp/services:restart", Methods: []string{"POST"}},
	{Group: "network", Name: "dhcp-services-start", Path: "/network/dhcp/services:start", Methods: []string{"POST"}},
	{Group: "network", Name: "dhcp-services-stop", Path: "/network/dhcp/services:stop", Methods: []string{"POST"}},
	{Group: "network", Name: "dhcp-static", Path: "/network/dhcp/static", Methods: []string{"GET", "POST", "PUT", "PATCH"}},
	{Group: "network", Name: "dhcp6-access-control-mode", Path: "/network/dhcp6/access-control/mode", Methods: []string{"GET", "PUT"}},
	{Group: "network", Name: "dhcp6-access-control-rules", Path: "/network/dhcp6/access-control/rules", Methods: []string{"GET", "POST", "PUT", "PATCH"}},
	{Group: "network", Name: "dhcp6-clients", Path: "/network/dhcp6/clients", Methods: []string{"GET"}},
	{Group: "network", Name: "dmz-rules", Path: "/network/dmz/rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "network", Name: "dnat-rules", Path: "/network/dnat/rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "network", Name: "dns-config", Path: "/network/dns/config", Methods: []string{"GET", "PUT"}},
	{Group: "network", Name: "dns-proxy-rules", Path: "/network/dns/proxy/rules", Methods: []string{"GET", "POST", "PUT"}},
	{Group: "network", Name: "dns-stats", Path: "/network/dns/stats", Methods: []string{"GET"}},
	{Group: "network", Name: "nat-rules", Path: "/network/nat/rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "network", Name: "pppoe-services", Path: "/network/pppoe/services", Methods: []string{"GET", "PUT"}},
	{Group: "network", Name: "qos-ip", Path: "/network/qos/ip", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "network", Name: "qos-mac", Path: "/network/qos/mac", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "network", Name: "vlan", Path: "/network/vlan", Methods: []string{"GET", "POST", "PUT", "PATCH"}},
	{Group: "objects", Name: "domain-objects", Path: "/domain-objects", Methods: []string{"GET", "POST", "PUT", "DELETE"}},
	{Group: "objects", Name: "ip-objects", Path: "/ip-objects", Methods: []string{"GET", "POST", "PUT", "DELETE"}},
	{Group: "objects", Name: "ipv6-objects", Path: "/ipv6-objects", Methods: []string{"GET", "POST", "PUT", "DELETE"}},
	{Group: "objects", Name: "mac-objects", Path: "/mac-objects", Methods: []string{"GET", "POST", "PUT", "DELETE"}},
	{Group: "objects", Name: "port-objects", Path: "/port-objects", Methods: []string{"GET", "POST", "PUT", "DELETE"}},
	{Group: "objects", Name: "protocol-objects", Path: "/protocol-objects", Methods: []string{"GET", "POST", "PUT", "DELETE"}},
	{Group: "objects", Name: "time-objects", Path: "/time-objects", Methods: []string{"GET", "POST", "PUT", "DELETE"}},
	{Group: "routing", Name: "app-protocols", Path: "/routing/app-protocols", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "routing", Name: "domain-rules", Path: "/routing/domain-rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "routing", Name: "five-tuple-rules", Path: "/routing/five-tuple-rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "routing", Name: "load-balance-rules", Path: "/routing/load-balance-rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "routing", Name: "static-routes", Path: "/routing/static-routes", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "routing", Name: "updown", Path: "/routing/updown", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "security", Name: "acl-rules", Path: "/security/acl-rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "security", Name: "advanced-config", Path: "/security/advanced/config", Methods: []string{"GET", "PUT"}},
	{Group: "security", Name: "app-protocols-professional-rules", Path: "/security/app-protocols/professional/rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "security", Name: "domain-blacklist-rules", Path: "/security/domain-blacklist/rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "security", Name: "mac-mode", Path: "/security/mac-mode", Methods: []string{"GET", "PUT"}},
	{Group: "security", Name: "mac-rules", Path: "/security/mac-rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "security", Name: "peerconn-rules", Path: "/security/peerconn/rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "security", Name: "secondary-route-config", Path: "/security/secondary-route/config", Methods: []string{"GET", "PUT"}},
	{Group: "security", Name: "terminals", Path: "/security/terminals", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "security", Name: "url-black-rules", Path: "/security/url-black/rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "security", Name: "url-keywords-rules", Path: "/security/url-keywords/rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "security", Name: "url-redirect-rules", Path: "/security/url-redirect/rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "security", Name: "url-replace-rules", Path: "/security/url-replace/rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "system", Name: "alg", Path: "/system/alg", Methods: []string{"GET", "PUT"}},
	{Group: "system", Name: "basic-config", Path: "/system/basic/config", Methods: []string{"GET", "PUT"}},
	{Group: "system", Name: "basic-ntp-sync", Path: "/system/basic/ntp:sync", Methods: []string{"POST"}},
	{Group: "system", Name: "cpufreq", Path: "/system/cpufreq", Methods: []string{"GET", "PUT"}},
	{Group: "system", Name: "cpufreq-mode", Path: "/system/cpufreq/mode", Methods: []string{"PUT"}},
	{Group: "system", Name: "kernel-params", Path: "/system/kernel-params", Methods: []string{"GET", "PUT"}},
	{Group: "system", Name: "reboot-schedules", Path: "/system/reboot-schedules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "system", Name: "remote-access", Path: "/system/remote-access", Methods: []string{"GET", "PUT"}},
	{Group: "system", Name: "vrrp-config", Path: "/system/vrrp/config", Methods: []string{"GET", "PUT"}},
	{Group: "system", Name: "vrrp-start", Path: "/system/vrrp:start", Methods: []string{"POST"}},
	{Group: "system", Name: "vrrp-stop", Path: "/system/vrrp:stop", Methods: []string{"POST"}},
	{Group: "vpn", Name: "ikev2", Path: "/vpn/ikev2", Methods: []string{"GET", "PUT"}},
	{Group: "vpn", Name: "ikev2-clients", Path: "/vpn/ikev2/clients", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "vpn", Name: "ipsec-clients", Path: "/vpn/ipsec/clients", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "vpn", Name: "l2tp", Path: "/vpn/l2tp", Methods: []string{"GET", "PUT"}},
	{Group: "vpn", Name: "l2tp-clients", Path: "/vpn/l2tp/clients", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "vpn", Name: "openvpn", Path: "/vpn/openvpn", Methods: []string{"GET", "PUT"}},
	{Group: "vpn", Name: "openvpn-clients", Path: "/vpn/openvpn/clients", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "vpn", Name: "pptp", Path: "/vpn/pptp", Methods: []string{"GET", "PUT"}},
	{Group: "vpn", Name: "pptp-clients", Path: "/vpn/pptp/clients", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "vpn", Name: "wireguard", Path: "/vpn/wireguard", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "wireless", Name: "access-control-rules", Path: "/wireless/access-control/rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
	{Group: "wireless", Name: "vlan-rules", Path: "/wireless/vlan/rules", Methods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"}},
}

func V4EndpointsByGroup(group string) []V4Endpoint {
	var endpoints []V4Endpoint
	for _, endpoint := range V4EndpointCatalog {
		if endpoint.Group == group {
			endpoints = append(endpoints, endpoint)
		}
	}
	return endpoints
}

func V4EndpointByName(name string) (V4Endpoint, bool) {
	for _, endpoint := range V4EndpointCatalog {
		if endpoint.Name == name {
			return endpoint, true
		}
	}
	return V4Endpoint{}, false
}
