// Code generated by ikuai-api/codegen. DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	"strconv"
	ikuaiapi "github.com/zy84338719/ikuai-api"
)

// AdvancedService is the typed v4 entry point for the "advanced" group.
// Method names follow the catalog Name field (CamelCased); the
// underlying HTTP verb and path are documented above each method.
type AdvancedService struct {
	client *ikuaiapi.Client
}

// PathAdvanced is the v4 catalog table for this group; it is exported so
// callers can iterate endpoints or build dynamic requests.
var PathAdvanced = pathGroupAdvanced()

func pathGroupAdvanced() []V4Endpoint {
	src := ikuaiapi.V4EndpointCatalog
	out := make([]V4Endpoint, 0, 16)
	for _, ep := range src {
		if ep.Group == "advanced" {
			out = append(out, ep)
		}
	}
	return out
}


// AdvancedFtpConfig wraps advanced ftp-config.
//
// Methods: GET, PUT
//
// Path: /advanced-service/ftp-config
//
// Use ListAdvancedFtpConfig(ctx, opts...) for paginated reads.
// AdvancedFtpConfigListOptions configures paginated reads of AdvancedFtpConfig.
type AdvancedFtpConfigListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *AdvancedFtpConfigListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListAdvancedFtpConfig lists items at /advanced-service/ftp-config.
func (s *AdvancedService) ListAdvancedFtpConfig(ctx context.Context, opts *AdvancedFtpConfigListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/advanced-service/ftp-config", opts.query())
}

// GetAdvancedFtpConfig fetches one item at /advanced-service/ftp-config.
func (s *AdvancedService) GetAdvancedFtpConfig(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/advanced-service/ftp-config", q)
}

// UpdateAdvancedFtpConfig replaces the resource at /advanced-service/ftp-config.
func (s *AdvancedService) UpdateAdvancedFtpConfig(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/advanced-service/ftp-config", body)
	return err
}


// AdvancedFtpUsers wraps advanced ftp-users.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /advanced-service/ftp-users
//
// Use ListAdvancedFtpUsers(ctx, opts...) for paginated reads.
// AdvancedFtpUsersListOptions configures paginated reads of AdvancedFtpUsers.
type AdvancedFtpUsersListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *AdvancedFtpUsersListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListAdvancedFtpUsers lists items at /advanced-service/ftp-users.
func (s *AdvancedService) ListAdvancedFtpUsers(ctx context.Context, opts *AdvancedFtpUsersListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/advanced-service/ftp-users", opts.query())
}

// GetAdvancedFtpUsers fetches one item at /advanced-service/ftp-users.
func (s *AdvancedService) GetAdvancedFtpUsers(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/advanced-service/ftp-users", q)
}

// CreateAdvancedFtpUsers posts a new item to /advanced-service/ftp-users. The router returns a rowid on
// success which is propagated to the caller.
func (s *AdvancedService) CreateAdvancedFtpUsers(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/advanced-service/ftp-users", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateAdvancedFtpUsers replaces the resource at /advanced-service/ftp-users.
func (s *AdvancedService) UpdateAdvancedFtpUsers(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/advanced-service/ftp-users", body)
	return err
}

// PatchAdvancedFtpUsers partial-updates the resource at /advanced-service/ftp-users.
func (s *AdvancedService) PatchAdvancedFtpUsers(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/advanced-service/ftp-users", body)
	return err
}

// DeleteAdvancedFtpUsers removes the resource at /advanced-service/ftp-users. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteAdvancedFtpUsersWithBody to send a custom JSON body instead.
func (s *AdvancedService) DeleteAdvancedFtpUsers(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/advanced-service/ftp-users"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteAdvancedFtpUsersWithBody removes the resource at /advanced-service/ftp-users with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteAdvancedFtpUsers cannot model directly).
func (s *AdvancedService) DeleteAdvancedFtpUsersWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/advanced-service/ftp-users", body)
	return err
}


// AdvancedHttpUsers wraps advanced http-users.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /advanced-service/http-users
//
// Use ListAdvancedHttpUsers(ctx, opts...) for paginated reads.
// AdvancedHttpUsersListOptions configures paginated reads of AdvancedHttpUsers.
type AdvancedHttpUsersListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *AdvancedHttpUsersListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListAdvancedHttpUsers lists items at /advanced-service/http-users.
func (s *AdvancedService) ListAdvancedHttpUsers(ctx context.Context, opts *AdvancedHttpUsersListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/advanced-service/http-users", opts.query())
}

// GetAdvancedHttpUsers fetches one item at /advanced-service/http-users.
func (s *AdvancedService) GetAdvancedHttpUsers(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/advanced-service/http-users", q)
}

// CreateAdvancedHttpUsers posts a new item to /advanced-service/http-users. The router returns a rowid on
// success which is propagated to the caller.
func (s *AdvancedService) CreateAdvancedHttpUsers(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/advanced-service/http-users", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateAdvancedHttpUsers replaces the resource at /advanced-service/http-users.
func (s *AdvancedService) UpdateAdvancedHttpUsers(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/advanced-service/http-users", body)
	return err
}

// PatchAdvancedHttpUsers partial-updates the resource at /advanced-service/http-users.
func (s *AdvancedService) PatchAdvancedHttpUsers(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/advanced-service/http-users", body)
	return err
}

// DeleteAdvancedHttpUsers removes the resource at /advanced-service/http-users. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteAdvancedHttpUsersWithBody to send a custom JSON body instead.
func (s *AdvancedService) DeleteAdvancedHttpUsers(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/advanced-service/http-users"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteAdvancedHttpUsersWithBody removes the resource at /advanced-service/http-users with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteAdvancedHttpUsers cannot model directly).
func (s *AdvancedService) DeleteAdvancedHttpUsersWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/advanced-service/http-users", body)
	return err
}


// AdvancedSambaConfig wraps advanced samba-config.
//
// Methods: GET, PUT
//
// Path: /advanced-service/samba-config
//
// Use ListAdvancedSambaConfig(ctx, opts...) for paginated reads.
// AdvancedSambaConfigListOptions configures paginated reads of AdvancedSambaConfig.
type AdvancedSambaConfigListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *AdvancedSambaConfigListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListAdvancedSambaConfig lists items at /advanced-service/samba-config.
func (s *AdvancedService) ListAdvancedSambaConfig(ctx context.Context, opts *AdvancedSambaConfigListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/advanced-service/samba-config", opts.query())
}

// GetAdvancedSambaConfig fetches one item at /advanced-service/samba-config.
func (s *AdvancedService) GetAdvancedSambaConfig(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/advanced-service/samba-config", q)
}

// UpdateAdvancedSambaConfig replaces the resource at /advanced-service/samba-config.
func (s *AdvancedService) UpdateAdvancedSambaConfig(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/advanced-service/samba-config", body)
	return err
}


// AdvancedSambaUsers wraps advanced samba-users.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /advanced-service/samba-users
//
// Use ListAdvancedSambaUsers(ctx, opts...) for paginated reads.
// AdvancedSambaUsersListOptions configures paginated reads of AdvancedSambaUsers.
type AdvancedSambaUsersListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *AdvancedSambaUsersListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListAdvancedSambaUsers lists items at /advanced-service/samba-users.
func (s *AdvancedService) ListAdvancedSambaUsers(ctx context.Context, opts *AdvancedSambaUsersListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/advanced-service/samba-users", opts.query())
}

// GetAdvancedSambaUsers fetches one item at /advanced-service/samba-users.
func (s *AdvancedService) GetAdvancedSambaUsers(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/advanced-service/samba-users", q)
}

// CreateAdvancedSambaUsers posts a new item to /advanced-service/samba-users. The router returns a rowid on
// success which is propagated to the caller.
func (s *AdvancedService) CreateAdvancedSambaUsers(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/advanced-service/samba-users", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateAdvancedSambaUsers replaces the resource at /advanced-service/samba-users.
func (s *AdvancedService) UpdateAdvancedSambaUsers(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/advanced-service/samba-users", body)
	return err
}

// PatchAdvancedSambaUsers partial-updates the resource at /advanced-service/samba-users.
func (s *AdvancedService) PatchAdvancedSambaUsers(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/advanced-service/samba-users", body)
	return err
}

// DeleteAdvancedSambaUsers removes the resource at /advanced-service/samba-users. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteAdvancedSambaUsersWithBody to send a custom JSON body instead.
func (s *AdvancedService) DeleteAdvancedSambaUsers(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/advanced-service/samba-users"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteAdvancedSambaUsersWithBody removes the resource at /advanced-service/samba-users with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteAdvancedSambaUsers cannot model directly).
func (s *AdvancedService) DeleteAdvancedSambaUsersWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/advanced-service/samba-users", body)
	return err
}


// AdvancedSnmpdConfig wraps advanced snmpd-config.
//
// Methods: GET, PUT
//
// Path: /advanced-service/snmpd-config
//
// Use ListAdvancedSnmpdConfig(ctx, opts...) for paginated reads.
// AdvancedSnmpdConfigListOptions configures paginated reads of AdvancedSnmpdConfig.
type AdvancedSnmpdConfigListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *AdvancedSnmpdConfigListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListAdvancedSnmpdConfig lists items at /advanced-service/snmpd-config.
func (s *AdvancedService) ListAdvancedSnmpdConfig(ctx context.Context, opts *AdvancedSnmpdConfigListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/advanced-service/snmpd-config", opts.query())
}

// GetAdvancedSnmpdConfig fetches one item at /advanced-service/snmpd-config.
func (s *AdvancedService) GetAdvancedSnmpdConfig(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/advanced-service/snmpd-config", q)
}

// UpdateAdvancedSnmpdConfig replaces the resource at /advanced-service/snmpd-config.
func (s *AdvancedService) UpdateAdvancedSnmpdConfig(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/advanced-service/snmpd-config", body)
	return err
}

