// Code generated by ikuai-api/codegen. DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	"strconv"
	ikuaiapi "github.com/zy84338719/ikuai-api"
)

// AuthService is the typed v4 entry point for the "auth" group.
// Method names follow the catalog Name field (CamelCased); the
// underlying HTTP verb and path are documented above each method.
type AuthService struct {
	client *ikuaiapi.Client
}

// PathAuth is the v4 catalog table for this group; it is exported so
// callers can iterate endpoints or build dynamic requests.
var PathAuth = pathGroupAuth()

func pathGroupAuth() []V4Endpoint {
	src := ikuaiapi.V4EndpointCatalog
	out := make([]V4Endpoint, 0, 16)
	for _, ep := range src {
		if ep.Group == "auth" {
			out = append(out, ep)
		}
	}
	return out
}


// AuthOnlineUsers wraps auth online-users.
//
// Methods: GET, DELETE
//
// Path: /auth/online-users
//
// Use ListAuthOnlineUsers(ctx, opts...) for paginated reads.
// AuthOnlineUsersListOptions configures paginated reads of AuthOnlineUsers.
type AuthOnlineUsersListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *AuthOnlineUsersListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListAuthOnlineUsers lists items at /auth/online-users.
func (s *AuthService) ListAuthOnlineUsers(ctx context.Context, opts *AuthOnlineUsersListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/auth/online-users", opts.query())
}

// GetAuthOnlineUsers fetches one item at /auth/online-users.
func (s *AuthService) GetAuthOnlineUsers(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/auth/online-users", q)
}

// DeleteAuthOnlineUsers removes the resource at /auth/online-users. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteAuthOnlineUsersWithBody to send a custom JSON body instead.
func (s *AuthService) DeleteAuthOnlineUsers(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/auth/online-users"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteAuthOnlineUsersWithBody removes the resource at /auth/online-users with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteAuthOnlineUsers cannot model directly).
func (s *AuthService) DeleteAuthOnlineUsersWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/auth/online-users", body)
	return err
}


// AuthPackages wraps auth packages.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /auth/packages
//
// Use ListAuthPackages(ctx, opts...) for paginated reads.
// AuthPackagesListOptions configures paginated reads of AuthPackages.
type AuthPackagesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *AuthPackagesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListAuthPackages lists items at /auth/packages.
func (s *AuthService) ListAuthPackages(ctx context.Context, opts *AuthPackagesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/auth/packages", opts.query())
}

// GetAuthPackages fetches one item at /auth/packages.
func (s *AuthService) GetAuthPackages(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/auth/packages", q)
}

// CreateAuthPackages posts a new item to /auth/packages. The router returns a rowid on
// success which is propagated to the caller.
func (s *AuthService) CreateAuthPackages(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/auth/packages", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateAuthPackages replaces the resource at /auth/packages.
func (s *AuthService) UpdateAuthPackages(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/auth/packages", body)
	return err
}

// PatchAuthPackages partial-updates the resource at /auth/packages.
func (s *AuthService) PatchAuthPackages(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/auth/packages", body)
	return err
}

// DeleteAuthPackages removes the resource at /auth/packages. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteAuthPackagesWithBody to send a custom JSON body instead.
func (s *AuthService) DeleteAuthPackages(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/auth/packages"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteAuthPackagesWithBody removes the resource at /auth/packages with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteAuthPackages cannot model directly).
func (s *AuthService) DeleteAuthPackagesWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/auth/packages", body)
	return err
}


// AuthUsers wraps auth users.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /auth/users
//
// Use ListAuthUsers(ctx, opts...) for paginated reads.
// AuthUsersListOptions configures paginated reads of AuthUsers.
type AuthUsersListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *AuthUsersListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListAuthUsers lists items at /auth/users.
func (s *AuthService) ListAuthUsers(ctx context.Context, opts *AuthUsersListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/auth/users", opts.query())
}

// GetAuthUsers fetches one item at /auth/users.
func (s *AuthService) GetAuthUsers(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/auth/users", q)
}

// CreateAuthUsers posts a new item to /auth/users. The router returns a rowid on
// success which is propagated to the caller.
func (s *AuthService) CreateAuthUsers(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/auth/users", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateAuthUsers replaces the resource at /auth/users.
func (s *AuthService) UpdateAuthUsers(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/auth/users", body)
	return err
}

// PatchAuthUsers partial-updates the resource at /auth/users.
func (s *AuthService) PatchAuthUsers(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/auth/users", body)
	return err
}

// DeleteAuthUsers removes the resource at /auth/users. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteAuthUsersWithBody to send a custom JSON body instead.
func (s *AuthService) DeleteAuthUsers(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/auth/users"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteAuthUsersWithBody removes the resource at /auth/users with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteAuthUsers cannot model directly).
func (s *AuthService) DeleteAuthUsersWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/auth/users", body)
	return err
}


// AuthWebServices wraps auth web-services.
//
// Methods: GET, PUT
//
// Path: /auth/web/services
//
// Use ListAuthWebServices(ctx, opts...) for paginated reads.
// AuthWebServicesListOptions configures paginated reads of AuthWebServices.
type AuthWebServicesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *AuthWebServicesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListAuthWebServices lists items at /auth/web/services.
func (s *AuthService) ListAuthWebServices(ctx context.Context, opts *AuthWebServicesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/auth/web/services", opts.query())
}

// GetAuthWebServices fetches one item at /auth/web/services.
func (s *AuthService) GetAuthWebServices(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/auth/web/services", q)
}

// UpdateAuthWebServices replaces the resource at /auth/web/services.
func (s *AuthService) UpdateAuthWebServices(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/auth/web/services", body)
	return err
}


// Field hints for this group (iKuai firmware field names):
//   username         Auth user name (required)
//   password         Auth user password (raw, not md5)
//   group_id         Group id (1-based; required)
//   enabled          yes | no
//   comment          Free-form comment
//   ip_addr          Bind IP (optional)
//   sesstimeout      Session timeout in seconds (0 = no limit)
