// Code generated by ikuai-api/codegen. DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	ikuaiapi "github.com/zy84338719/ikuai-api"
)

// InterfacesService is the typed v4 entry point for the "interfaces" group.
// Method names follow the catalog Name field (CamelCased); the
// underlying HTTP verb and path are documented above each method.
type InterfacesService struct {
	client *ikuaiapi.Client
}

// PathInterfaces is the v4 catalog table for this group; it is exported so
// callers can iterate endpoints or build dynamic requests.
var PathInterfaces = pathGroupInterfaces()

func pathGroupInterfaces() []V4Endpoint {
	src := ikuaiapi.V4EndpointCatalog
	out := make([]V4Endpoint, 0, 16)
	for _, ep := range src {
		if ep.Group == "interfaces" {
			out = append(out, ep)
		}
	}
	return out
}

// InterfacesLanConfig wraps interfaces lan-config.
//
// Methods: GET
//
// Path: /interfaces/lan-config
//
// Use ListInterfacesLanConfig(ctx, opts...) for paginated reads.
func (s *InterfacesService) GetInterfacesLanConfig(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/interfaces/lan-config", nil)
}

// InterfacesPhysical wraps interfaces physical.
//
// Methods: GET
//
// Path: /interfaces/physical
//
// Use ListInterfacesPhysical(ctx, opts...) for paginated reads.
func (s *InterfacesService) GetInterfacesPhysical(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/interfaces/physical", nil)
}

// InterfacesWanConfig wraps interfaces wan-config.
//
// Methods: GET
//
// Path: /interfaces/wan-config
//
// Use ListInterfacesWanConfig(ctx, opts...) for paginated reads.
func (s *InterfacesService) GetInterfacesWanConfig(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/interfaces/wan-config", nil)
}

// InterfacesWanVlanConfig wraps interfaces wan-vlan-config.
//
// Methods: GET
//
// Path: /interfaces/wan-vlan-config
//
// Use ListInterfacesWanVlanConfig(ctx, opts...) for paginated reads.
func (s *InterfacesService) GetInterfacesWanVlanConfig(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/interfaces/wan-vlan-config", nil)
}
