// Code generated by ikuai-api/codegen. DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	ikuaiapi "github.com/zy84338719/ikuai-api"
	"strconv"
)

// LogService is the typed v4 entry point for the "log" group.
// Method names follow the catalog Name field (CamelCased); the
// underlying HTTP verb and path are documented above each method.
type LogService struct {
	client *ikuaiapi.Client
}

// PathLog is the v4 catalog table for this group; it is exported so
// callers can iterate endpoints or build dynamic requests.
var PathLog = pathGroupLog()

func pathGroupLog() []V4Endpoint {
	src := ikuaiapi.V4EndpointCatalog
	out := make([]V4Endpoint, 0, 16)
	for _, ep := range src {
		if ep.Group == "log" {
			out = append(out, ep)
		}
	}
	return out
}

// LogArp wraps log arp.
//
// Methods: GET, DELETE
//
// Path: /log/arp
//
// Use ListLogArp(ctx, opts...) for paginated reads.
// LogArpListOptions configures paginated reads of LogArp.
type LogArpListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *LogArpListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListLogArp lists items at /log/arp.
func (s *LogService) ListLogArp(ctx context.Context, opts *LogArpListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/log/arp", opts.query())
}

// GetLogArp fetches one item at /log/arp.
func (s *LogService) GetLogArp(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/log/arp", q)
}

// DeleteLogArp removes the resource at /log/arp.
func (s *LogService) DeleteLogArp(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/log/arp", map[string]any{"id": id})
	return err
}

// LogAuth wraps log auth.
//
// Methods: GET, DELETE
//
// Path: /log/auth
//
// Use ListLogAuth(ctx, opts...) for paginated reads.
// LogAuthListOptions configures paginated reads of LogAuth.
type LogAuthListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *LogAuthListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListLogAuth lists items at /log/auth.
func (s *LogService) ListLogAuth(ctx context.Context, opts *LogAuthListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/log/auth", opts.query())
}

// GetLogAuth fetches one item at /log/auth.
func (s *LogService) GetLogAuth(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/log/auth", q)
}

// DeleteLogAuth removes the resource at /log/auth.
func (s *LogService) DeleteLogAuth(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/log/auth", map[string]any{"id": id})
	return err
}

// LogDdns wraps log ddns.
//
// Methods: GET, DELETE
//
// Path: /log/ddns
//
// Use ListLogDdns(ctx, opts...) for paginated reads.
// LogDdnsListOptions configures paginated reads of LogDdns.
type LogDdnsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *LogDdnsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListLogDdns lists items at /log/ddns.
func (s *LogService) ListLogDdns(ctx context.Context, opts *LogDdnsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/log/ddns", opts.query())
}

// GetLogDdns fetches one item at /log/ddns.
func (s *LogService) GetLogDdns(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/log/ddns", q)
}

// DeleteLogDdns removes the resource at /log/ddns.
func (s *LogService) DeleteLogDdns(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/log/ddns", map[string]any{"id": id})
	return err
}

// LogDhcp wraps log dhcp.
//
// Methods: GET, DELETE
//
// Path: /log/dhcp
//
// Use ListLogDhcp(ctx, opts...) for paginated reads.
// LogDhcpListOptions configures paginated reads of LogDhcp.
type LogDhcpListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *LogDhcpListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListLogDhcp lists items at /log/dhcp.
func (s *LogService) ListLogDhcp(ctx context.Context, opts *LogDhcpListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/log/dhcp", opts.query())
}

// GetLogDhcp fetches one item at /log/dhcp.
func (s *LogService) GetLogDhcp(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/log/dhcp", q)
}

// DeleteLogDhcp removes the resource at /log/dhcp.
func (s *LogService) DeleteLogDhcp(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/log/dhcp", map[string]any{"id": id})
	return err
}

// LogNotice wraps log notice.
//
// Methods: GET, DELETE
//
// Path: /log/notice
//
// Use ListLogNotice(ctx, opts...) for paginated reads.
// LogNoticeListOptions configures paginated reads of LogNotice.
type LogNoticeListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *LogNoticeListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListLogNotice lists items at /log/notice.
func (s *LogService) ListLogNotice(ctx context.Context, opts *LogNoticeListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/log/notice", opts.query())
}

// GetLogNotice fetches one item at /log/notice.
func (s *LogService) GetLogNotice(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/log/notice", q)
}

// DeleteLogNotice removes the resource at /log/notice.
func (s *LogService) DeleteLogNotice(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/log/notice", map[string]any{"id": id})
	return err
}

// LogPppoe wraps log pppoe.
//
// Methods: GET, DELETE
//
// Path: /log/pppoe
//
// Use ListLogPppoe(ctx, opts...) for paginated reads.
// LogPppoeListOptions configures paginated reads of LogPppoe.
type LogPppoeListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *LogPppoeListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListLogPppoe lists items at /log/pppoe.
func (s *LogService) ListLogPppoe(ctx context.Context, opts *LogPppoeListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/log/pppoe", opts.query())
}

// GetLogPppoe fetches one item at /log/pppoe.
func (s *LogService) GetLogPppoe(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/log/pppoe", q)
}

// DeleteLogPppoe removes the resource at /log/pppoe.
func (s *LogService) DeleteLogPppoe(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/log/pppoe", map[string]any{"id": id})
	return err
}

// LogSystem wraps log system.
//
// Methods: GET, DELETE
//
// Path: /log/system
//
// Use ListLogSystem(ctx, opts...) for paginated reads.
// LogSystemListOptions configures paginated reads of LogSystem.
type LogSystemListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *LogSystemListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListLogSystem lists items at /log/system.
func (s *LogService) ListLogSystem(ctx context.Context, opts *LogSystemListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/log/system", opts.query())
}

// GetLogSystem fetches one item at /log/system.
func (s *LogService) GetLogSystem(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/log/system", q)
}

// DeleteLogSystem removes the resource at /log/system.
func (s *LogService) DeleteLogSystem(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/log/system", map[string]any{"id": id})
	return err
}

// LogWebActivity wraps log web-activity.
//
// Methods: GET, DELETE
//
// Path: /log/web_activity
//
// Use ListLogWebActivity(ctx, opts...) for paginated reads.
// LogWebActivityListOptions configures paginated reads of LogWebActivity.
type LogWebActivityListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *LogWebActivityListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListLogWebActivity lists items at /log/web_activity.
func (s *LogService) ListLogWebActivity(ctx context.Context, opts *LogWebActivityListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/log/web_activity", opts.query())
}

// GetLogWebActivity fetches one item at /log/web_activity.
func (s *LogService) GetLogWebActivity(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/log/web_activity", q)
}

// DeleteLogWebActivity removes the resource at /log/web_activity.
func (s *LogService) DeleteLogWebActivity(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/log/web_activity", map[string]any{"id": id})
	return err
}

// LogWireless wraps log wireless.
//
// Methods: GET, DELETE
//
// Path: /log/wireless
//
// Use ListLogWireless(ctx, opts...) for paginated reads.
// LogWirelessListOptions configures paginated reads of LogWireless.
type LogWirelessListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *LogWirelessListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListLogWireless lists items at /log/wireless.
func (s *LogService) ListLogWireless(ctx context.Context, opts *LogWirelessListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/log/wireless", opts.query())
}

// GetLogWireless fetches one item at /log/wireless.
func (s *LogService) GetLogWireless(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/log/wireless", q)
}

// DeleteLogWireless removes the resource at /log/wireless.
func (s *LogService) DeleteLogWireless(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/log/wireless", map[string]any{"id": id})
	return err
}
