// Code generated by ikuai-api/codegen. DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	ikuaiapi "github.com/zy84338719/ikuai-api"
)

// MonitoringService is the typed v4 entry point for the "monitoring" group.
// Method names follow the catalog Name field (CamelCased); the
// underlying HTTP verb and path are documented above each method.
type MonitoringService struct {
	client *ikuaiapi.Client
}

// PathMonitoring is the v4 catalog table for this group; it is exported so
// callers can iterate endpoints or build dynamic requests.
var PathMonitoring = pathGroupMonitoring()

func pathGroupMonitoring() []V4Endpoint {
	src := ikuaiapi.V4EndpointCatalog
	out := make([]V4Endpoint, 0, 16)
	for _, ep := range src {
		if ep.Group == "monitoring" {
			out = append(out, ep)
		}
	}
	return out
}

// MonitoringAppProtocolsHistoryLoad wraps monitoring app-protocols-history-load.
//
// Methods: GET
//
// Path: /monitoring/app-protocols/history-load
//
// Use ListMonitoringAppProtocolsHistoryLoad(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringAppProtocolsHistoryLoad(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/app-protocols/history-load", nil)
}

// MonitoringAppProtocolsLoad wraps monitoring app-protocols-load.
//
// Methods: GET
//
// Path: /monitoring/app-protocols/load
//
// Use ListMonitoringAppProtocolsLoad(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringAppProtocolsLoad(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/app-protocols/load", nil)
}

// MonitoringAppProtocolsTerminalLoad wraps monitoring app-protocols-terminal-load.
//
// Methods: GET
//
// Path: /monitoring/app-protocols/terminal-load
//
// Use ListMonitoringAppProtocolsTerminalLoad(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringAppProtocolsTerminalLoad(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/app-protocols/terminal-load", nil)
}

// MonitoringAppTrafficSummary wraps monitoring app-traffic-summary.
//
// Methods: GET
//
// Path: /monitoring/app-traffic-summary
//
// Use ListMonitoringAppTrafficSummary(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringAppTrafficSummary(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/app-traffic-summary", nil)
}

// MonitoringCameras wraps monitoring cameras.
//
// Methods: GET
//
// Path: /monitoring/cameras
//
// Use ListMonitoringCameras(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringCameras(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/cameras", nil)
}

// MonitoringChannelClients wraps monitoring channel-clients.
//
// Methods: GET
//
// Path: /monitoring/channel-clients
//
// Use ListMonitoringChannelClients(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringChannelClients(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/channel-clients", nil)
}

// MonitoringClientsAppProtocolsLoad wraps monitoring clients-app-protocols-load.
//
// Methods: GET
//
// Path: /monitoring/clients/app-protocols/load
//
// Use ListMonitoringClientsAppProtocolsLoad(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsAppProtocolsLoad(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients/app-protocols/load", nil)
}

// MonitoringClientsIp6Offline wraps monitoring clients-ip6-offline.
//
// Methods: GET
//
// Path: /monitoring/clients-ip6-offline
//
// Use ListMonitoringClientsIp6Offline(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsIp6Offline(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients-ip6-offline", nil)
}

// MonitoringClientsIp6Online wraps monitoring clients-ip6-online.
//
// Methods: GET
//
// Path: /monitoring/clients-ip6-online
//
// Use ListMonitoringClientsIp6Online(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsIp6Online(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients-ip6-online", nil)
}

// MonitoringClientsOffline wraps monitoring clients-offline.
//
// Methods: GET
//
// Path: /monitoring/clients-offline
//
// Use ListMonitoringClientsOffline(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsOffline(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients-offline", nil)
}

// MonitoringClientsOnline wraps monitoring clients-online.
//
// Methods: GET
//
// Path: /monitoring/clients-online
//
// Use ListMonitoringClientsOnline(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsOnline(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients-online", nil)
}

// MonitoringClientsProtocols wraps monitoring clients-protocols.
//
// Methods: GET
//
// Path: /monitoring/clients/protocols
//
// Use ListMonitoringClientsProtocols(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsProtocols(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients/protocols", nil)
}

// MonitoringClientsProtocolsHistoryLoad wraps monitoring clients-protocols-history-load.
//
// Methods: GET
//
// Path: /monitoring/clients/protocols/history-load
//
// Use ListMonitoringClientsProtocolsHistoryLoad(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsProtocolsHistoryLoad(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients/protocols/history-load", nil)
}

// MonitoringClientsTrafficLoad wraps monitoring clients-traffic-load.
//
// Methods: GET
//
// Path: /monitoring/clients-traffic-load
//
// Use ListMonitoringClientsTrafficLoad(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsTrafficLoad(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients-traffic-load", nil)
}

// MonitoringClientsTrafficSummary wraps monitoring clients-traffic-summary.
//
// Methods: GET
//
// Path: /monitoring/clients-traffic-summary
//
// Use ListMonitoringClientsTrafficSummary(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsTrafficSummary(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients-traffic-summary", nil)
}

// MonitoringConnections wraps monitoring connections.
//
// Methods: GET
//
// Path: /monitoring/connections
//
// Use ListMonitoringConnections(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringConnections(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/connections", nil)
}

// MonitoringCpu wraps monitoring cpu.
//
// Methods: GET
//
// Path: /monitoring/cpu
//
// Use ListMonitoringCpu(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringCpu(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/cpu", nil)
}

// MonitoringCputemp wraps monitoring cputemp.
//
// Methods: GET
//
// Path: /monitoring/cputemp
//
// Use ListMonitoringCputemp(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringCputemp(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/cputemp", nil)
}

// MonitoringDisk wraps monitoring disk.
//
// Methods: GET
//
// Path: /monitoring/disk
//
// Use ListMonitoringDisk(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringDisk(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/disk", nil)
}

// MonitoringDownstream wraps monitoring downstream.
//
// Methods: GET
//
// Path: /monitoring/downstream
//
// Use ListMonitoringDownstream(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringDownstream(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/downstream", nil)
}

// MonitoringFlowShunting wraps monitoring flow-shunting.
//
// Methods: GET
//
// Path: /monitoring/flow-shunting
//
// Use ListMonitoringFlowShunting(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringFlowShunting(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/flow-shunting", nil)
}

// MonitoringInterfacesConfig wraps monitoring interfaces-config.
//
// Methods: GET
//
// Path: /monitoring/interfaces-config
//
// Use ListMonitoringInterfacesConfig(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringInterfacesConfig(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/interfaces-config", nil)
}

// MonitoringInterfacesPhysical wraps monitoring interfaces-physical.
//
// Methods: GET
//
// Path: /monitoring/interfaces-physical
//
// Use ListMonitoringInterfacesPhysical(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringInterfacesPhysical(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/interfaces-physical", nil)
}

// MonitoringInterfacesStatus wraps monitoring interfaces-status.
//
// Methods: GET
//
// Path: /monitoring/interfaces-status
//
// Use ListMonitoringInterfacesStatus(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringInterfacesStatus(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/interfaces-status", nil)
}

// MonitoringInterfacesTraffic wraps monitoring interfaces-traffic.
//
// Methods: GET
//
// Path: /monitoring/interfaces-traffic
//
// Use ListMonitoringInterfacesTraffic(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringInterfacesTraffic(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/interfaces-traffic", nil)
}

// MonitoringInterfacesTrafficV6 wraps monitoring interfaces-traffic-v6.
//
// Methods: GET
//
// Path: /monitoring/interfaces-traffic-v6
//
// Use ListMonitoringInterfacesTrafficV6(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringInterfacesTrafficV6(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/interfaces-traffic-v6", nil)
}

// MonitoringMemory wraps monitoring memory.
//
// Methods: GET
//
// Path: /monitoring/memory
//
// Use ListMonitoringMemory(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringMemory(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/memory", nil)
}

// MonitoringNetwork wraps monitoring network.
//
// Methods: GET
//
// Path: /monitoring/network
//
// Use ListMonitoringNetwork(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringNetwork(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/network", nil)
}

// MonitoringProtocols wraps monitoring protocols.
//
// Methods: GET
//
// Path: /monitoring/protocols
//
// Use ListMonitoringProtocols(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringProtocols(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/protocols", nil)
}

// MonitoringProtocolsHistoryLoad wraps monitoring protocols-history-load.
//
// Methods: GET
//
// Path: /monitoring/protocols/history-load
//
// Use ListMonitoringProtocolsHistoryLoad(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringProtocolsHistoryLoad(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/protocols/history-load", nil)
}

// MonitoringSsidClients wraps monitoring ssid-clients.
//
// Methods: GET
//
// Path: /monitoring/ssid-clients
//
// Use ListMonitoringSsidClients(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringSsidClients(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/ssid-clients", nil)
}

// MonitoringSwitch wraps monitoring switch.
//
// Methods: GET
//
// Path: /monitoring/switch
//
// Use ListMonitoringSwitch(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringSwitch(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/switch", nil)
}

// MonitoringSystem wraps monitoring system.
//
// Methods: GET
//
// Path: /monitoring/system
//
// Use ListMonitoringSystem(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringSystem(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/system", nil)
}

// MonitoringTerminals wraps monitoring terminals.
//
// Methods: GET
//
// Path: /monitoring/terminals
//
// Use ListMonitoringTerminals(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringTerminals(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/terminals", nil)
}

// MonitoringWirelessScore wraps monitoring wireless-score.
//
// Methods: GET
//
// Path: /monitoring/wireless-score
//
// Use ListMonitoringWirelessScore(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringWirelessScore(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/wireless-score", nil)
}

// MonitoringWirelessStatistics wraps monitoring wireless-statistics.
//
// Methods: GET
//
// Path: /monitoring/wireless-statistics
//
// Use ListMonitoringWirelessStatistics(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringWirelessStatistics(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/wireless-statistics", nil)
}

// MonitoringWirelessTraffic wraps monitoring wireless-traffic.
//
// Methods: GET
//
// Path: /monitoring/wireless-traffic
//
// Use ListMonitoringWirelessTraffic(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringWirelessTraffic(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/wireless-traffic", nil)
}
