// Code generated by ikuai-api/codegen. DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	"strconv"
	ikuaiapi "github.com/zy84338719/ikuai-api"
)

// MonitoringService is the typed v4 entry point for the "monitoring" group.
// Method names follow the catalog Name field (CamelCased); the
// underlying HTTP verb and path are documented above each method.
type MonitoringService struct {
	client *ikuaiapi.Client
}

// PathMonitoring is the v4 catalog table for this group; it is exported so
// callers can iterate endpoints or build dynamic requests.
var PathMonitoring = pathGroupMonitoring()

func pathGroupMonitoring() []V4Endpoint {
	src := ikuaiapi.V4EndpointCatalog
	out := make([]V4Endpoint, 0, 16)
	for _, ep := range src {
		if ep.Group == "monitoring" {
			out = append(out, ep)
		}
	}
	return out
}


// MonitoringAppProtocolsHistoryLoad wraps monitoring app-protocols-history-load.
//
// Methods: GET
//
// Path: /monitoring/app-protocols/history-load
//
// Use ListMonitoringAppProtocolsHistoryLoad(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringAppProtocolsHistoryLoad(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/app-protocols/history-load", nil)
}


// MonitoringAppProtocolsLoad wraps monitoring app-protocols-load.
//
// Methods: GET
//
// Path: /monitoring/app-protocols/load
//
// Use ListMonitoringAppProtocolsLoad(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringAppProtocolsLoad(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/app-protocols/load", nil)
}


// MonitoringAppProtocolsTerminalLoad wraps monitoring app-protocols-terminal-load.
//
// Methods: GET
//
// Path: /monitoring/app-protocols/terminal-load
//
// Use ListMonitoringAppProtocolsTerminalLoad(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringAppProtocolsTerminalLoad(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/app-protocols/terminal-load", nil)
}


// MonitoringAppTrafficSummary wraps monitoring app-traffic-summary.
//
// Methods: GET
//
// Path: /monitoring/app-traffic-summary
//
// Use ListMonitoringAppTrafficSummary(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringAppTrafficSummary(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/app-traffic-summary", nil)
}


// MonitoringCameras wraps monitoring cameras.
//
// Methods: GET
//
// Path: /monitoring/cameras
//
// Use ListMonitoringCameras(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringCameras(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/cameras", nil)
}


// MonitoringChannelClients wraps monitoring channel-clients.
//
// Methods: GET
//
// Path: /monitoring/channel-clients
//
// Use ListMonitoringChannelClients(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringChannelClients(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/channel-clients", nil)
}


// MonitoringClientsAppProtocolsLoad wraps monitoring clients-app-protocols-load.
//
// Methods: GET
//
// Path: /monitoring/clients/app-protocols/load
//
// Use ListMonitoringClientsAppProtocolsLoad(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsAppProtocolsLoad(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients/app-protocols/load", nil)
}


// MonitoringClientsIp6Offline wraps monitoring clients-ip6-offline.
//
// Methods: GET
//
// Path: /monitoring/clients-ip6-offline
//
// Use ListMonitoringClientsIp6Offline(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsIp6Offline(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients-ip6-offline", nil)
}


// MonitoringClientsIp6Online wraps monitoring clients-ip6-online.
//
// Methods: GET
//
// Path: /monitoring/clients-ip6-online
//
// Use ListMonitoringClientsIp6Online(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsIp6Online(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients-ip6-online", nil)
}


// MonitoringClientsOffline wraps monitoring clients-offline.
//
// Methods: GET
//
// Path: /monitoring/clients-offline
//
// Use ListMonitoringClientsOffline(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsOffline(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients-offline", nil)
}


// MonitoringClientsOnline wraps monitoring clients-online.
//
// Methods: GET
//
// Path: /monitoring/clients-online
//
// Use ListMonitoringClientsOnline(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsOnline(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients-online", nil)
}


// MonitoringClientsProtocols wraps monitoring clients-protocols.
//
// Methods: GET
//
// Path: /monitoring/clients/protocols
//
// Use ListMonitoringClientsProtocols(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsProtocols(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients/protocols", nil)
}


// MonitoringClientsProtocolsHistoryLoad wraps monitoring clients-protocols-history-load.
//
// Methods: GET
//
// Path: /monitoring/clients/protocols/history-load
//
// Use ListMonitoringClientsProtocolsHistoryLoad(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsProtocolsHistoryLoad(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients/protocols/history-load", nil)
}


// MonitoringClientsTrafficLoad wraps monitoring clients-traffic-load.
//
// Methods: GET
//
// Path: /monitoring/clients-traffic-load
//
// Use ListMonitoringClientsTrafficLoad(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsTrafficLoad(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients-traffic-load", nil)
}


// MonitoringClientsTrafficSummary wraps monitoring clients-traffic-summary.
//
// Methods: GET
//
// Path: /monitoring/clients-traffic-summary
//
// Use ListMonitoringClientsTrafficSummary(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringClientsTrafficSummary(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/clients-traffic-summary", nil)
}


// MonitoringConnections wraps monitoring connections.
//
// Methods: GET
//
// Path: /monitoring/connections
//
// Use ListMonitoringConnections(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringConnections(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/connections", nil)
}


// MonitoringCpu wraps monitoring cpu.
//
// Methods: GET
//
// Path: /monitoring/cpu
// MonitoringCpuLoadOptions configures a load query against /monitoring/cpu.
// All fields are required; the router rejects partial queries.
//
// DataType selects the time bucket. iKuai accepts one of
// "hour", "day", "week", "month".
//
// Math is the aggregation. iKuai accepts one of "avg", "max".
//
// StartTime / EndTime are Unix epoch seconds. StartTime must be
// strictly less than EndTime.
type MonitoringCpuLoadOptions struct {
	DataType  string
	StartTime int64
	EndTime   int64
	Math      string
}

func (o *MonitoringCpuLoadOptions) query() (map[string]string, error) {
	if o == nil {
		return nil, &ikuaiapi.APIError{Message: "MonitoringCpuLoadOptions: options are required"}
	}
	switch o.DataType {
	case "hour", "day", "week", "month":
	default:
		return nil, &ikuaiapi.APIError{Message: "MonitoringCpuLoadOptions: DataType must be one of: hour, day, week, month"}
	}
	switch o.Math {
	case "avg", "max":
	default:
		return nil, &ikuaiapi.APIError{Message: "MonitoringCpuLoadOptions: Math must be one of: avg, max"}
	}
	if o.StartTime <= 0 || o.EndTime <= 0 {
		return nil, &ikuaiapi.APIError{Message: "MonitoringCpuLoadOptions: StartTime and EndTime are required (Unix seconds)"}
	}
	if o.StartTime >= o.EndTime {
		return nil, &ikuaiapi.APIError{Message: "MonitoringCpuLoadOptions: StartTime must be less than EndTime"}
	}
	return map[string]string{
		"datetype":   o.DataType,
		"start_time": strconv.FormatInt(o.StartTime, 10),
		"end_time":   strconv.FormatInt(o.EndTime, 10),
		"math":       o.Math,
	}, nil
}

// LoadCpu runs a typed load query against /monitoring/cpu.
func (s *MonitoringService) LoadCpu(ctx context.Context, opts *MonitoringCpuLoadOptions) (json.RawMessage, error) {
	q, err := opts.query()
	if err != nil {
		return nil, err
	}
	return s.client.Get(ctx, "/monitoring/cpu", q)
}


// MonitoringCputemp wraps monitoring cputemp.
//
// Methods: GET
//
// Path: /monitoring/cputemp
// MonitoringCputempLoadOptions configures a load query against /monitoring/cputemp.
// All fields are required; the router rejects partial queries.
//
// DataType selects the time bucket. iKuai accepts one of
// "hour", "day", "week", "month".
//
// Math is the aggregation. iKuai accepts one of "avg", "max".
//
// StartTime / EndTime are Unix epoch seconds. StartTime must be
// strictly less than EndTime.
type MonitoringCputempLoadOptions struct {
	DataType  string
	StartTime int64
	EndTime   int64
	Math      string
}

func (o *MonitoringCputempLoadOptions) query() (map[string]string, error) {
	if o == nil {
		return nil, &ikuaiapi.APIError{Message: "MonitoringCputempLoadOptions: options are required"}
	}
	switch o.DataType {
	case "hour", "day", "week", "month":
	default:
		return nil, &ikuaiapi.APIError{Message: "MonitoringCputempLoadOptions: DataType must be one of: hour, day, week, month"}
	}
	switch o.Math {
	case "avg", "max":
	default:
		return nil, &ikuaiapi.APIError{Message: "MonitoringCputempLoadOptions: Math must be one of: avg, max"}
	}
	if o.StartTime <= 0 || o.EndTime <= 0 {
		return nil, &ikuaiapi.APIError{Message: "MonitoringCputempLoadOptions: StartTime and EndTime are required (Unix seconds)"}
	}
	if o.StartTime >= o.EndTime {
		return nil, &ikuaiapi.APIError{Message: "MonitoringCputempLoadOptions: StartTime must be less than EndTime"}
	}
	return map[string]string{
		"datetype":   o.DataType,
		"start_time": strconv.FormatInt(o.StartTime, 10),
		"end_time":   strconv.FormatInt(o.EndTime, 10),
		"math":       o.Math,
	}, nil
}

// LoadCputemp runs a typed load query against /monitoring/cputemp.
func (s *MonitoringService) LoadCputemp(ctx context.Context, opts *MonitoringCputempLoadOptions) (json.RawMessage, error) {
	q, err := opts.query()
	if err != nil {
		return nil, err
	}
	return s.client.Get(ctx, "/monitoring/cputemp", q)
}


// MonitoringDisk wraps monitoring disk.
//
// Methods: GET
//
// Path: /monitoring/disk
// MonitoringDiskLoadOptions configures a load query against /monitoring/disk.
// All fields are required; the router rejects partial queries.
//
// DataType selects the time bucket. iKuai accepts one of
// "hour", "day", "week", "month".
//
// Math is the aggregation. iKuai accepts one of "avg", "max".
//
// StartTime / EndTime are Unix epoch seconds. StartTime must be
// strictly less than EndTime.
type MonitoringDiskLoadOptions struct {
	DataType  string
	StartTime int64
	EndTime   int64
	Math      string
}

func (o *MonitoringDiskLoadOptions) query() (map[string]string, error) {
	if o == nil {
		return nil, &ikuaiapi.APIError{Message: "MonitoringDiskLoadOptions: options are required"}
	}
	switch o.DataType {
	case "hour", "day", "week", "month":
	default:
		return nil, &ikuaiapi.APIError{Message: "MonitoringDiskLoadOptions: DataType must be one of: hour, day, week, month"}
	}
	switch o.Math {
	case "avg", "max":
	default:
		return nil, &ikuaiapi.APIError{Message: "MonitoringDiskLoadOptions: Math must be one of: avg, max"}
	}
	if o.StartTime <= 0 || o.EndTime <= 0 {
		return nil, &ikuaiapi.APIError{Message: "MonitoringDiskLoadOptions: StartTime and EndTime are required (Unix seconds)"}
	}
	if o.StartTime >= o.EndTime {
		return nil, &ikuaiapi.APIError{Message: "MonitoringDiskLoadOptions: StartTime must be less than EndTime"}
	}
	return map[string]string{
		"datetype":   o.DataType,
		"start_time": strconv.FormatInt(o.StartTime, 10),
		"end_time":   strconv.FormatInt(o.EndTime, 10),
		"math":       o.Math,
	}, nil
}

// LoadDisk runs a typed load query against /monitoring/disk.
func (s *MonitoringService) LoadDisk(ctx context.Context, opts *MonitoringDiskLoadOptions) (json.RawMessage, error) {
	q, err := opts.query()
	if err != nil {
		return nil, err
	}
	return s.client.Get(ctx, "/monitoring/disk", q)
}


// MonitoringDownstream wraps monitoring downstream.
//
// Methods: GET
//
// Path: /monitoring/downstream
//
// Use ListMonitoringDownstream(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringDownstream(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/downstream", nil)
}


// MonitoringFlowShunting wraps monitoring flow-shunting.
//
// Methods: GET
//
// Path: /monitoring/flow-shunting
//
// Use ListMonitoringFlowShunting(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringFlowShunting(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/flow-shunting", nil)
}


// MonitoringInterfacesConfig wraps monitoring interfaces-config.
//
// Methods: GET
//
// Path: /monitoring/interfaces-config
//
// Use ListMonitoringInterfacesConfig(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringInterfacesConfig(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/interfaces-config", nil)
}


// MonitoringInterfacesPhysical wraps monitoring interfaces-physical.
//
// Methods: GET
//
// Path: /monitoring/interfaces-physical
//
// Use ListMonitoringInterfacesPhysical(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringInterfacesPhysical(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/interfaces-physical", nil)
}


// MonitoringInterfacesStatus wraps monitoring interfaces-status.
//
// Methods: GET
//
// Path: /monitoring/interfaces-status
//
// Use ListMonitoringInterfacesStatus(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringInterfacesStatus(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/interfaces-status", nil)
}


// MonitoringInterfacesTraffic wraps monitoring interfaces-traffic.
//
// Methods: GET
//
// Path: /monitoring/interfaces-traffic
//
// Use ListMonitoringInterfacesTraffic(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringInterfacesTraffic(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/interfaces-traffic", nil)
}


// MonitoringInterfacesTrafficV6 wraps monitoring interfaces-traffic-v6.
//
// Methods: GET
//
// Path: /monitoring/interfaces-traffic-v6
//
// Use ListMonitoringInterfacesTrafficV6(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringInterfacesTrafficV6(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/interfaces-traffic-v6", nil)
}


// MonitoringMemory wraps monitoring memory.
//
// Methods: GET
//
// Path: /monitoring/memory
// MonitoringMemoryLoadOptions configures a load query against /monitoring/memory.
// All fields are required; the router rejects partial queries.
//
// DataType selects the time bucket. iKuai accepts one of
// "hour", "day", "week", "month".
//
// Math is the aggregation. iKuai accepts one of "avg", "max".
//
// StartTime / EndTime are Unix epoch seconds. StartTime must be
// strictly less than EndTime.
type MonitoringMemoryLoadOptions struct {
	DataType  string
	StartTime int64
	EndTime   int64
	Math      string
}

func (o *MonitoringMemoryLoadOptions) query() (map[string]string, error) {
	if o == nil {
		return nil, &ikuaiapi.APIError{Message: "MonitoringMemoryLoadOptions: options are required"}
	}
	switch o.DataType {
	case "hour", "day", "week", "month":
	default:
		return nil, &ikuaiapi.APIError{Message: "MonitoringMemoryLoadOptions: DataType must be one of: hour, day, week, month"}
	}
	switch o.Math {
	case "avg", "max":
	default:
		return nil, &ikuaiapi.APIError{Message: "MonitoringMemoryLoadOptions: Math must be one of: avg, max"}
	}
	if o.StartTime <= 0 || o.EndTime <= 0 {
		return nil, &ikuaiapi.APIError{Message: "MonitoringMemoryLoadOptions: StartTime and EndTime are required (Unix seconds)"}
	}
	if o.StartTime >= o.EndTime {
		return nil, &ikuaiapi.APIError{Message: "MonitoringMemoryLoadOptions: StartTime must be less than EndTime"}
	}
	return map[string]string{
		"datetype":   o.DataType,
		"start_time": strconv.FormatInt(o.StartTime, 10),
		"end_time":   strconv.FormatInt(o.EndTime, 10),
		"math":       o.Math,
	}, nil
}

// LoadMemory runs a typed load query against /monitoring/memory.
func (s *MonitoringService) LoadMemory(ctx context.Context, opts *MonitoringMemoryLoadOptions) (json.RawMessage, error) {
	q, err := opts.query()
	if err != nil {
		return nil, err
	}
	return s.client.Get(ctx, "/monitoring/memory", q)
}


// MonitoringNetwork wraps monitoring network.
//
// Methods: GET
//
// Path: /monitoring/network
//
// Use ListMonitoringNetwork(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringNetwork(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/network", nil)
}


// MonitoringProtocols wraps monitoring protocols.
//
// Methods: GET
//
// Path: /monitoring/protocols
//
// Use ListMonitoringProtocols(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringProtocols(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/protocols", nil)
}


// MonitoringProtocolsHistoryLoad wraps monitoring protocols-history-load.
//
// Methods: GET
//
// Path: /monitoring/protocols/history-load
//
// Use ListMonitoringProtocolsHistoryLoad(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringProtocolsHistoryLoad(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/protocols/history-load", nil)
}


// MonitoringSsidClients wraps monitoring ssid-clients.
//
// Methods: GET
//
// Path: /monitoring/ssid-clients
//
// Use ListMonitoringSsidClients(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringSsidClients(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/ssid-clients", nil)
}


// MonitoringSwitch wraps monitoring switch.
//
// Methods: GET
//
// Path: /monitoring/switch
//
// Use ListMonitoringSwitch(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringSwitch(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/switch", nil)
}


// MonitoringSystem wraps monitoring system.
//
// Methods: GET
//
// Path: /monitoring/system
//
// Use ListMonitoringSystem(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringSystem(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/system", nil)
}


// MonitoringTerminals wraps monitoring terminals.
//
// Methods: GET
//
// Path: /monitoring/terminals
// MonitoringTerminalsLoadOptions configures a load query against /monitoring/terminals.
// All fields are required; the router rejects partial queries.
//
// DataType selects the time bucket. iKuai accepts one of
// "hour", "day", "week", "month".
//
// Math is the aggregation. iKuai accepts one of "avg", "max".
//
// StartTime / EndTime are Unix epoch seconds. StartTime must be
// strictly less than EndTime.
type MonitoringTerminalsLoadOptions struct {
	DataType  string
	StartTime int64
	EndTime   int64
	Math      string
}

func (o *MonitoringTerminalsLoadOptions) query() (map[string]string, error) {
	if o == nil {
		return nil, &ikuaiapi.APIError{Message: "MonitoringTerminalsLoadOptions: options are required"}
	}
	switch o.DataType {
	case "hour", "day", "week", "month":
	default:
		return nil, &ikuaiapi.APIError{Message: "MonitoringTerminalsLoadOptions: DataType must be one of: hour, day, week, month"}
	}
	switch o.Math {
	case "avg", "max":
	default:
		return nil, &ikuaiapi.APIError{Message: "MonitoringTerminalsLoadOptions: Math must be one of: avg, max"}
	}
	if o.StartTime <= 0 || o.EndTime <= 0 {
		return nil, &ikuaiapi.APIError{Message: "MonitoringTerminalsLoadOptions: StartTime and EndTime are required (Unix seconds)"}
	}
	if o.StartTime >= o.EndTime {
		return nil, &ikuaiapi.APIError{Message: "MonitoringTerminalsLoadOptions: StartTime must be less than EndTime"}
	}
	return map[string]string{
		"datetype":   o.DataType,
		"start_time": strconv.FormatInt(o.StartTime, 10),
		"end_time":   strconv.FormatInt(o.EndTime, 10),
		"math":       o.Math,
	}, nil
}

// LoadTerminals runs a typed load query against /monitoring/terminals.
func (s *MonitoringService) LoadTerminals(ctx context.Context, opts *MonitoringTerminalsLoadOptions) (json.RawMessage, error) {
	q, err := opts.query()
	if err != nil {
		return nil, err
	}
	return s.client.Get(ctx, "/monitoring/terminals", q)
}


// MonitoringWirelessScore wraps monitoring wireless-score.
//
// Methods: GET
//
// Path: /monitoring/wireless-score
//
// Use ListMonitoringWirelessScore(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringWirelessScore(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/wireless-score", nil)
}


// MonitoringWirelessStatistics wraps monitoring wireless-statistics.
//
// Methods: GET
//
// Path: /monitoring/wireless-statistics
//
// Use ListMonitoringWirelessStatistics(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringWirelessStatistics(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/wireless-statistics", nil)
}


// MonitoringWirelessTraffic wraps monitoring wireless-traffic.
//
// Methods: GET
//
// Path: /monitoring/wireless-traffic
//
// Use ListMonitoringWirelessTraffic(ctx, opts...) for paginated reads.
func (s *MonitoringService) GetMonitoringWirelessTraffic(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/monitoring/wireless-traffic", nil)
}

