// Code generated by ikuai-api/codegen. DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	"strconv"
	ikuaiapi "github.com/zy84338719/ikuai-api"
)

// NetworkService is the typed v4 entry point for the "network" group.
// Method names follow the catalog Name field (CamelCased); the
// underlying HTTP verb and path are documented above each method.
type NetworkService struct {
	client *ikuaiapi.Client
}

// PathNetwork is the v4 catalog table for this group; it is exported so
// callers can iterate endpoints or build dynamic requests.
var PathNetwork = pathGroupNetwork()

func pathGroupNetwork() []V4Endpoint {
	src := ikuaiapi.V4EndpointCatalog
	out := make([]V4Endpoint, 0, 16)
	for _, ep := range src {
		if ep.Group == "network" {
			out = append(out, ep)
		}
	}
	return out
}


// NetworkAcApConfig wraps network ac-ap-config.
//
// Methods: GET, PUT, DELETE
//
// Path: /network/ac/ap-config
//
// Use ListNetworkAcApConfig(ctx, opts...) for paginated reads.
// NetworkAcApConfigListOptions configures paginated reads of NetworkAcApConfig.
type NetworkAcApConfigListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkAcApConfigListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkAcApConfig lists items at /network/ac/ap-config.
func (s *NetworkService) ListNetworkAcApConfig(ctx context.Context, opts *NetworkAcApConfigListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/ac/ap-config", opts.query())
}

// GetNetworkAcApConfig fetches one item at /network/ac/ap-config.
func (s *NetworkService) GetNetworkAcApConfig(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/ac/ap-config", q)
}

// UpdateNetworkAcApConfig replaces the resource at /network/ac/ap-config.
func (s *NetworkService) UpdateNetworkAcApConfig(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/ac/ap-config", body)
	return err
}

// DeleteNetworkAcApConfig removes the resource at /network/ac/ap-config. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteNetworkAcApConfigWithBody to send a custom JSON body instead.
func (s *NetworkService) DeleteNetworkAcApConfig(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/network/ac/ap-config"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteNetworkAcApConfigWithBody removes the resource at /network/ac/ap-config with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteNetworkAcApConfig cannot model directly).
func (s *NetworkService) DeleteNetworkAcApConfigWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/network/ac/ap-config", body)
	return err
}


// NetworkAcServices wraps network ac-services.
//
// Methods: GET, PUT
//
// Path: /network/ac/services
//
// Use ListNetworkAcServices(ctx, opts...) for paginated reads.
// NetworkAcServicesListOptions configures paginated reads of NetworkAcServices.
type NetworkAcServicesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkAcServicesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkAcServices lists items at /network/ac/services.
func (s *NetworkService) ListNetworkAcServices(ctx context.Context, opts *NetworkAcServicesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/ac/services", opts.query())
}

// GetNetworkAcServices fetches one item at /network/ac/services.
func (s *NetworkService) GetNetworkAcServices(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/ac/services", q)
}

// UpdateNetworkAcServices replaces the resource at /network/ac/services.
func (s *NetworkService) UpdateNetworkAcServices(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/ac/services", body)
	return err
}


// NetworkAcServicesStart wraps network ac-services-start.
//
// Methods: POST
//
// Path: /network/ac/services:start
// StartNetworkAcServices Start the resource at /network/ac/services:start. body is sent as JSON;
// pass nil if the action takes no parameters.
func (s *NetworkService) StartNetworkAcServices(ctx context.Context, body any) (json.RawMessage, error) {
	return s.client.Post(ctx, "/network/ac/services:start", body)
}


// NetworkAcServicesStop wraps network ac-services-stop.
//
// Methods: POST
//
// Path: /network/ac/services:stop
// StopNetworkAcServices Stop the resource at /network/ac/services:stop. No body is required.
func (s *NetworkService) StopNetworkAcServices(ctx context.Context) (json.RawMessage, error) {
	return s.client.Post(ctx, "/network/ac/services:stop", map[string]any{})
}


// NetworkDhcpAccessControlMode wraps network dhcp-access-control-mode.
//
// Methods: GET, PUT
//
// Path: /network/dhcp/access-control/mode
//
// Use ListNetworkDhcpAccessControlMode(ctx, opts...) for paginated reads.
// NetworkDhcpAccessControlModeListOptions configures paginated reads of NetworkDhcpAccessControlMode.
type NetworkDhcpAccessControlModeListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkDhcpAccessControlModeListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkDhcpAccessControlMode lists items at /network/dhcp/access-control/mode.
func (s *NetworkService) ListNetworkDhcpAccessControlMode(ctx context.Context, opts *NetworkDhcpAccessControlModeListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/dhcp/access-control/mode", opts.query())
}

// GetNetworkDhcpAccessControlMode fetches one item at /network/dhcp/access-control/mode.
func (s *NetworkService) GetNetworkDhcpAccessControlMode(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/dhcp/access-control/mode", q)
}

// UpdateNetworkDhcpAccessControlMode replaces the resource at /network/dhcp/access-control/mode.
func (s *NetworkService) UpdateNetworkDhcpAccessControlMode(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/dhcp/access-control/mode", body)
	return err
}


// NetworkDhcpAccessControlRules wraps network dhcp-access-control-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /network/dhcp/access-control/rules
//
// Use ListNetworkDhcpAccessControlRules(ctx, opts...) for paginated reads.
// NetworkDhcpAccessControlRulesListOptions configures paginated reads of NetworkDhcpAccessControlRules.
type NetworkDhcpAccessControlRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkDhcpAccessControlRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkDhcpAccessControlRules lists items at /network/dhcp/access-control/rules.
func (s *NetworkService) ListNetworkDhcpAccessControlRules(ctx context.Context, opts *NetworkDhcpAccessControlRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/dhcp/access-control/rules", opts.query())
}

// GetNetworkDhcpAccessControlRules fetches one item at /network/dhcp/access-control/rules.
func (s *NetworkService) GetNetworkDhcpAccessControlRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/dhcp/access-control/rules", q)
}

// CreateNetworkDhcpAccessControlRules posts a new item to /network/dhcp/access-control/rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *NetworkService) CreateNetworkDhcpAccessControlRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/network/dhcp/access-control/rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateNetworkDhcpAccessControlRules replaces the resource at /network/dhcp/access-control/rules.
func (s *NetworkService) UpdateNetworkDhcpAccessControlRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/dhcp/access-control/rules", body)
	return err
}

// PatchNetworkDhcpAccessControlRules partial-updates the resource at /network/dhcp/access-control/rules.
func (s *NetworkService) PatchNetworkDhcpAccessControlRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/network/dhcp/access-control/rules", body)
	return err
}

// DeleteNetworkDhcpAccessControlRules removes the resource at /network/dhcp/access-control/rules. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteNetworkDhcpAccessControlRulesWithBody to send a custom JSON body instead.
func (s *NetworkService) DeleteNetworkDhcpAccessControlRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/network/dhcp/access-control/rules"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteNetworkDhcpAccessControlRulesWithBody removes the resource at /network/dhcp/access-control/rules with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteNetworkDhcpAccessControlRules cannot model directly).
func (s *NetworkService) DeleteNetworkDhcpAccessControlRulesWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/network/dhcp/access-control/rules", body)
	return err
}


// NetworkDhcpClients wraps network dhcp-clients.
//
// Methods: GET
//
// Path: /network/dhcp/clients
//
// Use ListNetworkDhcpClients(ctx, opts...) for paginated reads.
func (s *NetworkService) GetNetworkDhcpClients(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/dhcp/clients", nil)
}


// NetworkDhcpServices wraps network dhcp-services.
//
// Methods: GET, POST, PUT, PATCH
//
// Path: /network/dhcp/services
//
// Use ListNetworkDhcpServices(ctx, opts...) for paginated reads.
// NetworkDhcpServicesListOptions configures paginated reads of NetworkDhcpServices.
type NetworkDhcpServicesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkDhcpServicesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkDhcpServices lists items at /network/dhcp/services.
func (s *NetworkService) ListNetworkDhcpServices(ctx context.Context, opts *NetworkDhcpServicesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/dhcp/services", opts.query())
}

// GetNetworkDhcpServices fetches one item at /network/dhcp/services.
func (s *NetworkService) GetNetworkDhcpServices(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/dhcp/services", q)
}

// CreateNetworkDhcpServices posts a new item to /network/dhcp/services. The router returns a rowid on
// success which is propagated to the caller.
func (s *NetworkService) CreateNetworkDhcpServices(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/network/dhcp/services", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateNetworkDhcpServices replaces the resource at /network/dhcp/services.
func (s *NetworkService) UpdateNetworkDhcpServices(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/dhcp/services", body)
	return err
}

// PatchNetworkDhcpServices partial-updates the resource at /network/dhcp/services.
func (s *NetworkService) PatchNetworkDhcpServices(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/network/dhcp/services", body)
	return err
}


// NetworkDhcpServicesRestart wraps network dhcp-services-restart.
//
// Methods: POST
//
// Path: /network/dhcp/services:restart
// RestartNetworkDhcpServices Restart the resource at /network/dhcp/services:restart. No body is required.
func (s *NetworkService) RestartNetworkDhcpServices(ctx context.Context) (json.RawMessage, error) {
	return s.client.Post(ctx, "/network/dhcp/services:restart", map[string]any{})
}


// NetworkDhcpServicesStart wraps network dhcp-services-start.
//
// Methods: POST
//
// Path: /network/dhcp/services:start
// StartNetworkDhcpServices Start the resource at /network/dhcp/services:start. body is sent as JSON;
// pass nil if the action takes no parameters.
func (s *NetworkService) StartNetworkDhcpServices(ctx context.Context, body any) (json.RawMessage, error) {
	return s.client.Post(ctx, "/network/dhcp/services:start", body)
}


// NetworkDhcpServicesStop wraps network dhcp-services-stop.
//
// Methods: POST
//
// Path: /network/dhcp/services:stop
// StopNetworkDhcpServices Stop the resource at /network/dhcp/services:stop. No body is required.
func (s *NetworkService) StopNetworkDhcpServices(ctx context.Context) (json.RawMessage, error) {
	return s.client.Post(ctx, "/network/dhcp/services:stop", map[string]any{})
}


// NetworkDhcpStatic wraps network dhcp-static.
//
// Methods: GET, POST, PUT, PATCH
//
// Path: /network/dhcp/static
//
// Use ListNetworkDhcpStatic(ctx, opts...) for paginated reads.
// NetworkDhcpStaticListOptions configures paginated reads of NetworkDhcpStatic.
type NetworkDhcpStaticListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkDhcpStaticListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkDhcpStatic lists items at /network/dhcp/static.
func (s *NetworkService) ListNetworkDhcpStatic(ctx context.Context, opts *NetworkDhcpStaticListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/dhcp/static", opts.query())
}

// GetNetworkDhcpStatic fetches one item at /network/dhcp/static.
func (s *NetworkService) GetNetworkDhcpStatic(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/dhcp/static", q)
}

// CreateNetworkDhcpStatic posts a new item to /network/dhcp/static. The router returns a rowid on
// success which is propagated to the caller.
func (s *NetworkService) CreateNetworkDhcpStatic(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/network/dhcp/static", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateNetworkDhcpStatic replaces the resource at /network/dhcp/static.
func (s *NetworkService) UpdateNetworkDhcpStatic(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/dhcp/static", body)
	return err
}

// PatchNetworkDhcpStatic partial-updates the resource at /network/dhcp/static.
func (s *NetworkService) PatchNetworkDhcpStatic(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/network/dhcp/static", body)
	return err
}


// NetworkDhcp6AccessControlMode wraps network dhcp6-access-control-mode.
//
// Methods: GET, PUT
//
// Path: /network/dhcp6/access-control/mode
//
// Use ListNetworkDhcp6AccessControlMode(ctx, opts...) for paginated reads.
// NetworkDhcp6AccessControlModeListOptions configures paginated reads of NetworkDhcp6AccessControlMode.
type NetworkDhcp6AccessControlModeListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkDhcp6AccessControlModeListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkDhcp6AccessControlMode lists items at /network/dhcp6/access-control/mode.
func (s *NetworkService) ListNetworkDhcp6AccessControlMode(ctx context.Context, opts *NetworkDhcp6AccessControlModeListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/dhcp6/access-control/mode", opts.query())
}

// GetNetworkDhcp6AccessControlMode fetches one item at /network/dhcp6/access-control/mode.
func (s *NetworkService) GetNetworkDhcp6AccessControlMode(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/dhcp6/access-control/mode", q)
}

// UpdateNetworkDhcp6AccessControlMode replaces the resource at /network/dhcp6/access-control/mode.
func (s *NetworkService) UpdateNetworkDhcp6AccessControlMode(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/dhcp6/access-control/mode", body)
	return err
}


// NetworkDhcp6AccessControlRules wraps network dhcp6-access-control-rules.
//
// Methods: GET, POST, PUT, PATCH
//
// Path: /network/dhcp6/access-control/rules
//
// Use ListNetworkDhcp6AccessControlRules(ctx, opts...) for paginated reads.
// NetworkDhcp6AccessControlRulesListOptions configures paginated reads of NetworkDhcp6AccessControlRules.
type NetworkDhcp6AccessControlRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkDhcp6AccessControlRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkDhcp6AccessControlRules lists items at /network/dhcp6/access-control/rules.
func (s *NetworkService) ListNetworkDhcp6AccessControlRules(ctx context.Context, opts *NetworkDhcp6AccessControlRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/dhcp6/access-control/rules", opts.query())
}

// GetNetworkDhcp6AccessControlRules fetches one item at /network/dhcp6/access-control/rules.
func (s *NetworkService) GetNetworkDhcp6AccessControlRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/dhcp6/access-control/rules", q)
}

// CreateNetworkDhcp6AccessControlRules posts a new item to /network/dhcp6/access-control/rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *NetworkService) CreateNetworkDhcp6AccessControlRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/network/dhcp6/access-control/rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateNetworkDhcp6AccessControlRules replaces the resource at /network/dhcp6/access-control/rules.
func (s *NetworkService) UpdateNetworkDhcp6AccessControlRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/dhcp6/access-control/rules", body)
	return err
}

// PatchNetworkDhcp6AccessControlRules partial-updates the resource at /network/dhcp6/access-control/rules.
func (s *NetworkService) PatchNetworkDhcp6AccessControlRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/network/dhcp6/access-control/rules", body)
	return err
}


// NetworkDhcp6Clients wraps network dhcp6-clients.
//
// Methods: GET
//
// Path: /network/dhcp6/clients
//
// Use ListNetworkDhcp6Clients(ctx, opts...) for paginated reads.
func (s *NetworkService) GetNetworkDhcp6Clients(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/dhcp6/clients", nil)
}


// NetworkDmzRules wraps network dmz-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /network/dmz/rules
//
// Use ListNetworkDmzRules(ctx, opts...) for paginated reads.
// NetworkDmzRulesListOptions configures paginated reads of NetworkDmzRules.
type NetworkDmzRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkDmzRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkDmzRules lists items at /network/dmz/rules.
func (s *NetworkService) ListNetworkDmzRules(ctx context.Context, opts *NetworkDmzRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/dmz/rules", opts.query())
}

// GetNetworkDmzRules fetches one item at /network/dmz/rules.
func (s *NetworkService) GetNetworkDmzRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/dmz/rules", q)
}

// CreateNetworkDmzRules posts a new item to /network/dmz/rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *NetworkService) CreateNetworkDmzRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/network/dmz/rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateNetworkDmzRules replaces the resource at /network/dmz/rules.
func (s *NetworkService) UpdateNetworkDmzRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/dmz/rules", body)
	return err
}

// PatchNetworkDmzRules partial-updates the resource at /network/dmz/rules.
func (s *NetworkService) PatchNetworkDmzRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/network/dmz/rules", body)
	return err
}

// DeleteNetworkDmzRules removes the resource at /network/dmz/rules. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteNetworkDmzRulesWithBody to send a custom JSON body instead.
func (s *NetworkService) DeleteNetworkDmzRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/network/dmz/rules"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteNetworkDmzRulesWithBody removes the resource at /network/dmz/rules with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteNetworkDmzRules cannot model directly).
func (s *NetworkService) DeleteNetworkDmzRulesWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/network/dmz/rules", body)
	return err
}


// NetworkDnatRules wraps network dnat-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /network/dnat/rules
//
// Use ListNetworkDnatRules(ctx, opts...) for paginated reads.
// NetworkDnatRulesListOptions configures paginated reads of NetworkDnatRules.
type NetworkDnatRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkDnatRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkDnatRules lists items at /network/dnat/rules.
func (s *NetworkService) ListNetworkDnatRules(ctx context.Context, opts *NetworkDnatRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/dnat/rules", opts.query())
}

// GetNetworkDnatRules fetches one item at /network/dnat/rules.
func (s *NetworkService) GetNetworkDnatRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/dnat/rules", q)
}

// CreateNetworkDnatRules posts a new item to /network/dnat/rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *NetworkService) CreateNetworkDnatRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/network/dnat/rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateNetworkDnatRules replaces the resource at /network/dnat/rules.
func (s *NetworkService) UpdateNetworkDnatRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/dnat/rules", body)
	return err
}

// PatchNetworkDnatRules partial-updates the resource at /network/dnat/rules.
func (s *NetworkService) PatchNetworkDnatRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/network/dnat/rules", body)
	return err
}

// DeleteNetworkDnatRules removes the resource at /network/dnat/rules. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteNetworkDnatRulesWithBody to send a custom JSON body instead.
func (s *NetworkService) DeleteNetworkDnatRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/network/dnat/rules"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteNetworkDnatRulesWithBody removes the resource at /network/dnat/rules with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteNetworkDnatRules cannot model directly).
func (s *NetworkService) DeleteNetworkDnatRulesWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/network/dnat/rules", body)
	return err
}


// NetworkDnsConfig wraps network dns-config.
//
// Methods: GET, PUT
//
// Path: /network/dns/config
//
// Use ListNetworkDnsConfig(ctx, opts...) for paginated reads.
// NetworkDnsConfigListOptions configures paginated reads of NetworkDnsConfig.
type NetworkDnsConfigListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkDnsConfigListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkDnsConfig lists items at /network/dns/config.
func (s *NetworkService) ListNetworkDnsConfig(ctx context.Context, opts *NetworkDnsConfigListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/dns/config", opts.query())
}

// GetNetworkDnsConfig fetches one item at /network/dns/config.
func (s *NetworkService) GetNetworkDnsConfig(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/dns/config", q)
}

// UpdateNetworkDnsConfig replaces the resource at /network/dns/config.
func (s *NetworkService) UpdateNetworkDnsConfig(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/dns/config", body)
	return err
}


// NetworkDnsProxyRules wraps network dns-proxy-rules.
//
// Methods: GET, POST, PUT
//
// Path: /network/dns/proxy/rules
//
// Use ListNetworkDnsProxyRules(ctx, opts...) for paginated reads.
// NetworkDnsProxyRulesListOptions configures paginated reads of NetworkDnsProxyRules.
type NetworkDnsProxyRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkDnsProxyRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkDnsProxyRules lists items at /network/dns/proxy/rules.
func (s *NetworkService) ListNetworkDnsProxyRules(ctx context.Context, opts *NetworkDnsProxyRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/dns/proxy/rules", opts.query())
}

// GetNetworkDnsProxyRules fetches one item at /network/dns/proxy/rules.
func (s *NetworkService) GetNetworkDnsProxyRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/dns/proxy/rules", q)
}

// CreateNetworkDnsProxyRules posts a new item to /network/dns/proxy/rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *NetworkService) CreateNetworkDnsProxyRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/network/dns/proxy/rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateNetworkDnsProxyRules replaces the resource at /network/dns/proxy/rules.
func (s *NetworkService) UpdateNetworkDnsProxyRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/dns/proxy/rules", body)
	return err
}


// NetworkDnsStats wraps network dns-stats.
//
// Methods: GET
//
// Path: /network/dns/stats
//
// Use ListNetworkDnsStats(ctx, opts...) for paginated reads.
func (s *NetworkService) GetNetworkDnsStats(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/dns/stats", nil)
}


// NetworkNatRules wraps network nat-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /network/nat/rules
//
// Use ListNetworkNatRules(ctx, opts...) for paginated reads.
// NetworkNatRulesListOptions configures paginated reads of NetworkNatRules.
type NetworkNatRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkNatRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkNatRules lists items at /network/nat/rules.
func (s *NetworkService) ListNetworkNatRules(ctx context.Context, opts *NetworkNatRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/nat/rules", opts.query())
}

// GetNetworkNatRules fetches one item at /network/nat/rules.
func (s *NetworkService) GetNetworkNatRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/nat/rules", q)
}

// CreateNetworkNatRules posts a new item to /network/nat/rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *NetworkService) CreateNetworkNatRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/network/nat/rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateNetworkNatRules replaces the resource at /network/nat/rules.
func (s *NetworkService) UpdateNetworkNatRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/nat/rules", body)
	return err
}

// PatchNetworkNatRules partial-updates the resource at /network/nat/rules.
func (s *NetworkService) PatchNetworkNatRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/network/nat/rules", body)
	return err
}

// DeleteNetworkNatRules removes the resource at /network/nat/rules. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteNetworkNatRulesWithBody to send a custom JSON body instead.
func (s *NetworkService) DeleteNetworkNatRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/network/nat/rules"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteNetworkNatRulesWithBody removes the resource at /network/nat/rules with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteNetworkNatRules cannot model directly).
func (s *NetworkService) DeleteNetworkNatRulesWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/network/nat/rules", body)
	return err
}


// NetworkPppoeServices wraps network pppoe-services.
//
// Methods: GET, PUT
//
// Path: /network/pppoe/services
//
// Use ListNetworkPppoeServices(ctx, opts...) for paginated reads.
// NetworkPppoeServicesListOptions configures paginated reads of NetworkPppoeServices.
type NetworkPppoeServicesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkPppoeServicesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkPppoeServices lists items at /network/pppoe/services.
func (s *NetworkService) ListNetworkPppoeServices(ctx context.Context, opts *NetworkPppoeServicesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/pppoe/services", opts.query())
}

// GetNetworkPppoeServices fetches one item at /network/pppoe/services.
func (s *NetworkService) GetNetworkPppoeServices(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/pppoe/services", q)
}

// UpdateNetworkPppoeServices replaces the resource at /network/pppoe/services.
func (s *NetworkService) UpdateNetworkPppoeServices(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/pppoe/services", body)
	return err
}


// NetworkQosIp wraps network qos-ip.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /network/qos/ip
//
// Use ListNetworkQosIp(ctx, opts...) for paginated reads.
// NetworkQosIpListOptions configures paginated reads of NetworkQosIp.
type NetworkQosIpListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkQosIpListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkQosIp lists items at /network/qos/ip.
func (s *NetworkService) ListNetworkQosIp(ctx context.Context, opts *NetworkQosIpListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/qos/ip", opts.query())
}

// GetNetworkQosIp fetches one item at /network/qos/ip.
func (s *NetworkService) GetNetworkQosIp(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/qos/ip", q)
}

// CreateNetworkQosIp posts a new item to /network/qos/ip. The router returns a rowid on
// success which is propagated to the caller.
func (s *NetworkService) CreateNetworkQosIp(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/network/qos/ip", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateNetworkQosIp replaces the resource at /network/qos/ip.
func (s *NetworkService) UpdateNetworkQosIp(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/qos/ip", body)
	return err
}

// PatchNetworkQosIp partial-updates the resource at /network/qos/ip.
func (s *NetworkService) PatchNetworkQosIp(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/network/qos/ip", body)
	return err
}

// DeleteNetworkQosIp removes the resource at /network/qos/ip. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteNetworkQosIpWithBody to send a custom JSON body instead.
func (s *NetworkService) DeleteNetworkQosIp(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/network/qos/ip"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteNetworkQosIpWithBody removes the resource at /network/qos/ip with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteNetworkQosIp cannot model directly).
func (s *NetworkService) DeleteNetworkQosIpWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/network/qos/ip", body)
	return err
}


// NetworkQosMac wraps network qos-mac.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /network/qos/mac
//
// Use ListNetworkQosMac(ctx, opts...) for paginated reads.
// NetworkQosMacListOptions configures paginated reads of NetworkQosMac.
type NetworkQosMacListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkQosMacListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkQosMac lists items at /network/qos/mac.
func (s *NetworkService) ListNetworkQosMac(ctx context.Context, opts *NetworkQosMacListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/qos/mac", opts.query())
}

// GetNetworkQosMac fetches one item at /network/qos/mac.
func (s *NetworkService) GetNetworkQosMac(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/qos/mac", q)
}

// CreateNetworkQosMac posts a new item to /network/qos/mac. The router returns a rowid on
// success which is propagated to the caller.
func (s *NetworkService) CreateNetworkQosMac(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/network/qos/mac", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateNetworkQosMac replaces the resource at /network/qos/mac.
func (s *NetworkService) UpdateNetworkQosMac(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/qos/mac", body)
	return err
}

// PatchNetworkQosMac partial-updates the resource at /network/qos/mac.
func (s *NetworkService) PatchNetworkQosMac(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/network/qos/mac", body)
	return err
}

// DeleteNetworkQosMac removes the resource at /network/qos/mac. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteNetworkQosMacWithBody to send a custom JSON body instead.
func (s *NetworkService) DeleteNetworkQosMac(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/network/qos/mac"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteNetworkQosMacWithBody removes the resource at /network/qos/mac with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteNetworkQosMac cannot model directly).
func (s *NetworkService) DeleteNetworkQosMacWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/network/qos/mac", body)
	return err
}


// NetworkVlan wraps network vlan.
//
// Methods: GET, POST, PUT, PATCH
//
// Path: /network/vlan
//
// Use ListNetworkVlan(ctx, opts...) for paginated reads.
// NetworkVlanListOptions configures paginated reads of NetworkVlan.
type NetworkVlanListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *NetworkVlanListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListNetworkVlan lists items at /network/vlan.
func (s *NetworkService) ListNetworkVlan(ctx context.Context, opts *NetworkVlanListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/network/vlan", opts.query())
}

// GetNetworkVlan fetches one item at /network/vlan.
func (s *NetworkService) GetNetworkVlan(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/network/vlan", q)
}

// CreateNetworkVlan posts a new item to /network/vlan. The router returns a rowid on
// success which is propagated to the caller.
func (s *NetworkService) CreateNetworkVlan(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/network/vlan", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateNetworkVlan replaces the resource at /network/vlan.
func (s *NetworkService) UpdateNetworkVlan(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/network/vlan", body)
	return err
}

// PatchNetworkVlan partial-updates the resource at /network/vlan.
func (s *NetworkService) PatchNetworkVlan(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/network/vlan", body)
	return err
}


// Field hints for this group (iKuai firmware field names):
//   name             Rule name (required for create, used in list views)
//   action           NAT action: filter | dnat | snat
//   protocol         Protocol: tcp | udp | any
//   in_interface     Inbound interface (wan1, lan1, …)
//   out_interface    Outbound interface
//   comment          Free-form comment, shown in the web UI
//   wan_port         WAN port (NAT rule). Single port, range, or comma list
//   lan_addr         LAN target address (DNAT). IP or CIDR
//   lan_port         LAN target port (DNAT)
//   src_addr         Source address(es). Comma-separated IP/CIDR groups
//   dst_addr         Destination address(es). Comma-separated IP/CIDR groups
//   src_port         Source port(s). Comma-separated ports/ranges
//   dst_port         Destination port(s). Comma-separated ports/ranges
//   enabled          yes | no. Whether the rule is active
