// Code generated by ikuai-api/codegen. DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	"strconv"
	ikuaiapi "github.com/zy84338719/ikuai-api"
)

// ObjectsService is the typed v4 entry point for the "objects" group.
// Method names follow the catalog Name field (CamelCased); the
// underlying HTTP verb and path are documented above each method.
type ObjectsService struct {
	client *ikuaiapi.Client
}

// PathObjects is the v4 catalog table for this group; it is exported so
// callers can iterate endpoints or build dynamic requests.
var PathObjects = pathGroupObjects()

func pathGroupObjects() []V4Endpoint {
	src := ikuaiapi.V4EndpointCatalog
	out := make([]V4Endpoint, 0, 16)
	for _, ep := range src {
		if ep.Group == "objects" {
			out = append(out, ep)
		}
	}
	return out
}


// ObjectsDomainObjects wraps objects domain-objects.
//
// Methods: GET, POST, PUT, DELETE
//
// Path: /domain-objects
//
// Use ListObjectsDomainObjects(ctx, opts...) for paginated reads.
// ObjectsDomainObjectsListOptions configures paginated reads of ObjectsDomainObjects.
type ObjectsDomainObjectsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *ObjectsDomainObjectsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListObjectsDomainObjects lists items at /domain-objects.
func (s *ObjectsService) ListObjectsDomainObjects(ctx context.Context, opts *ObjectsDomainObjectsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/domain-objects", opts.query())
}

// GetObjectsDomainObjects fetches one item at /domain-objects.
func (s *ObjectsService) GetObjectsDomainObjects(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/domain-objects", q)
}

// CreateObjectsDomainObjects posts a new item to /domain-objects. The router returns a rowid on
// success which is propagated to the caller.
func (s *ObjectsService) CreateObjectsDomainObjects(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/domain-objects", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateObjectsDomainObjects replaces the resource at /domain-objects.
func (s *ObjectsService) UpdateObjectsDomainObjects(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/domain-objects", body)
	return err
}

// DeleteObjectsDomainObjects removes the resource at /domain-objects. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteObjectsDomainObjectsWithBody to send a custom JSON body instead.
func (s *ObjectsService) DeleteObjectsDomainObjects(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/domain-objects"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteObjectsDomainObjectsWithBody removes the resource at /domain-objects with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteObjectsDomainObjects cannot model directly).
func (s *ObjectsService) DeleteObjectsDomainObjectsWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/domain-objects", body)
	return err
}


// ObjectsIpObjects wraps objects ip-objects.
//
// Methods: GET, POST, PUT, DELETE
//
// Path: /ip-objects
//
// Use ListObjectsIpObjects(ctx, opts...) for paginated reads.
// ObjectsIpObjectsListOptions configures paginated reads of ObjectsIpObjects.
type ObjectsIpObjectsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *ObjectsIpObjectsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListObjectsIpObjects lists items at /ip-objects.
func (s *ObjectsService) ListObjectsIpObjects(ctx context.Context, opts *ObjectsIpObjectsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/ip-objects", opts.query())
}

// GetObjectsIpObjects fetches one item at /ip-objects.
func (s *ObjectsService) GetObjectsIpObjects(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/ip-objects", q)
}

// CreateObjectsIpObjects posts a new item to /ip-objects. The router returns a rowid on
// success which is propagated to the caller.
func (s *ObjectsService) CreateObjectsIpObjects(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/ip-objects", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateObjectsIpObjects replaces the resource at /ip-objects.
func (s *ObjectsService) UpdateObjectsIpObjects(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/ip-objects", body)
	return err
}

// DeleteObjectsIpObjects removes the resource at /ip-objects. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteObjectsIpObjectsWithBody to send a custom JSON body instead.
func (s *ObjectsService) DeleteObjectsIpObjects(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/ip-objects"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteObjectsIpObjectsWithBody removes the resource at /ip-objects with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteObjectsIpObjects cannot model directly).
func (s *ObjectsService) DeleteObjectsIpObjectsWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/ip-objects", body)
	return err
}


// ObjectsIpv6Objects wraps objects ipv6-objects.
//
// Methods: GET, POST, PUT, DELETE
//
// Path: /ipv6-objects
//
// Use ListObjectsIpv6Objects(ctx, opts...) for paginated reads.
// ObjectsIpv6ObjectsListOptions configures paginated reads of ObjectsIpv6Objects.
type ObjectsIpv6ObjectsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *ObjectsIpv6ObjectsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListObjectsIpv6Objects lists items at /ipv6-objects.
func (s *ObjectsService) ListObjectsIpv6Objects(ctx context.Context, opts *ObjectsIpv6ObjectsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/ipv6-objects", opts.query())
}

// GetObjectsIpv6Objects fetches one item at /ipv6-objects.
func (s *ObjectsService) GetObjectsIpv6Objects(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/ipv6-objects", q)
}

// CreateObjectsIpv6Objects posts a new item to /ipv6-objects. The router returns a rowid on
// success which is propagated to the caller.
func (s *ObjectsService) CreateObjectsIpv6Objects(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/ipv6-objects", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateObjectsIpv6Objects replaces the resource at /ipv6-objects.
func (s *ObjectsService) UpdateObjectsIpv6Objects(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/ipv6-objects", body)
	return err
}

// DeleteObjectsIpv6Objects removes the resource at /ipv6-objects. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteObjectsIpv6ObjectsWithBody to send a custom JSON body instead.
func (s *ObjectsService) DeleteObjectsIpv6Objects(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/ipv6-objects"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteObjectsIpv6ObjectsWithBody removes the resource at /ipv6-objects with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteObjectsIpv6Objects cannot model directly).
func (s *ObjectsService) DeleteObjectsIpv6ObjectsWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/ipv6-objects", body)
	return err
}


// ObjectsMacObjects wraps objects mac-objects.
//
// Methods: GET, POST, PUT, DELETE
//
// Path: /mac-objects
//
// Use ListObjectsMacObjects(ctx, opts...) for paginated reads.
// ObjectsMacObjectsListOptions configures paginated reads of ObjectsMacObjects.
type ObjectsMacObjectsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *ObjectsMacObjectsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListObjectsMacObjects lists items at /mac-objects.
func (s *ObjectsService) ListObjectsMacObjects(ctx context.Context, opts *ObjectsMacObjectsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/mac-objects", opts.query())
}

// GetObjectsMacObjects fetches one item at /mac-objects.
func (s *ObjectsService) GetObjectsMacObjects(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/mac-objects", q)
}

// CreateObjectsMacObjects posts a new item to /mac-objects. The router returns a rowid on
// success which is propagated to the caller.
func (s *ObjectsService) CreateObjectsMacObjects(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/mac-objects", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateObjectsMacObjects replaces the resource at /mac-objects.
func (s *ObjectsService) UpdateObjectsMacObjects(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/mac-objects", body)
	return err
}

// DeleteObjectsMacObjects removes the resource at /mac-objects. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteObjectsMacObjectsWithBody to send a custom JSON body instead.
func (s *ObjectsService) DeleteObjectsMacObjects(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/mac-objects"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteObjectsMacObjectsWithBody removes the resource at /mac-objects with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteObjectsMacObjects cannot model directly).
func (s *ObjectsService) DeleteObjectsMacObjectsWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/mac-objects", body)
	return err
}


// ObjectsPortObjects wraps objects port-objects.
//
// Methods: GET, POST, PUT, DELETE
//
// Path: /port-objects
//
// Use ListObjectsPortObjects(ctx, opts...) for paginated reads.
// ObjectsPortObjectsListOptions configures paginated reads of ObjectsPortObjects.
type ObjectsPortObjectsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *ObjectsPortObjectsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListObjectsPortObjects lists items at /port-objects.
func (s *ObjectsService) ListObjectsPortObjects(ctx context.Context, opts *ObjectsPortObjectsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/port-objects", opts.query())
}

// GetObjectsPortObjects fetches one item at /port-objects.
func (s *ObjectsService) GetObjectsPortObjects(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/port-objects", q)
}

// CreateObjectsPortObjects posts a new item to /port-objects. The router returns a rowid on
// success which is propagated to the caller.
func (s *ObjectsService) CreateObjectsPortObjects(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/port-objects", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateObjectsPortObjects replaces the resource at /port-objects.
func (s *ObjectsService) UpdateObjectsPortObjects(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/port-objects", body)
	return err
}

// DeleteObjectsPortObjects removes the resource at /port-objects. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteObjectsPortObjectsWithBody to send a custom JSON body instead.
func (s *ObjectsService) DeleteObjectsPortObjects(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/port-objects"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteObjectsPortObjectsWithBody removes the resource at /port-objects with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteObjectsPortObjects cannot model directly).
func (s *ObjectsService) DeleteObjectsPortObjectsWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/port-objects", body)
	return err
}


// ObjectsProtocolObjects wraps objects protocol-objects.
//
// Methods: GET, POST, PUT, DELETE
//
// Path: /protocol-objects
//
// Use ListObjectsProtocolObjects(ctx, opts...) for paginated reads.
// ObjectsProtocolObjectsListOptions configures paginated reads of ObjectsProtocolObjects.
type ObjectsProtocolObjectsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *ObjectsProtocolObjectsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListObjectsProtocolObjects lists items at /protocol-objects.
func (s *ObjectsService) ListObjectsProtocolObjects(ctx context.Context, opts *ObjectsProtocolObjectsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/protocol-objects", opts.query())
}

// GetObjectsProtocolObjects fetches one item at /protocol-objects.
func (s *ObjectsService) GetObjectsProtocolObjects(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/protocol-objects", q)
}

// CreateObjectsProtocolObjects posts a new item to /protocol-objects. The router returns a rowid on
// success which is propagated to the caller.
func (s *ObjectsService) CreateObjectsProtocolObjects(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/protocol-objects", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateObjectsProtocolObjects replaces the resource at /protocol-objects.
func (s *ObjectsService) UpdateObjectsProtocolObjects(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/protocol-objects", body)
	return err
}

// DeleteObjectsProtocolObjects removes the resource at /protocol-objects. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteObjectsProtocolObjectsWithBody to send a custom JSON body instead.
func (s *ObjectsService) DeleteObjectsProtocolObjects(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/protocol-objects"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteObjectsProtocolObjectsWithBody removes the resource at /protocol-objects with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteObjectsProtocolObjects cannot model directly).
func (s *ObjectsService) DeleteObjectsProtocolObjectsWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/protocol-objects", body)
	return err
}


// ObjectsTimeObjects wraps objects time-objects.
//
// Methods: GET, POST, PUT, DELETE
//
// Path: /time-objects
//
// Use ListObjectsTimeObjects(ctx, opts...) for paginated reads.
// ObjectsTimeObjectsListOptions configures paginated reads of ObjectsTimeObjects.
type ObjectsTimeObjectsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *ObjectsTimeObjectsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListObjectsTimeObjects lists items at /time-objects.
func (s *ObjectsService) ListObjectsTimeObjects(ctx context.Context, opts *ObjectsTimeObjectsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/time-objects", opts.query())
}

// GetObjectsTimeObjects fetches one item at /time-objects.
func (s *ObjectsService) GetObjectsTimeObjects(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/time-objects", q)
}

// CreateObjectsTimeObjects posts a new item to /time-objects. The router returns a rowid on
// success which is propagated to the caller.
func (s *ObjectsService) CreateObjectsTimeObjects(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/time-objects", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateObjectsTimeObjects replaces the resource at /time-objects.
func (s *ObjectsService) UpdateObjectsTimeObjects(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/time-objects", body)
	return err
}

// DeleteObjectsTimeObjects removes the resource at /time-objects. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteObjectsTimeObjectsWithBody to send a custom JSON body instead.
func (s *ObjectsService) DeleteObjectsTimeObjects(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/time-objects"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteObjectsTimeObjectsWithBody removes the resource at /time-objects with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteObjectsTimeObjects cannot model directly).
func (s *ObjectsService) DeleteObjectsTimeObjectsWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/time-objects", body)
	return err
}


// Field hints for this group (iKuai firmware field names):
//   name             Object name (required)
//   comment          Free-form comment
//   ip_group         Array of IP/CIDR strings (for ip-objects)
//   mac              MAC address (for mac-objects)
//   port_group       Array of port strings (for port-objects)
//   domain_group     Array of domain strings (for domain-objects)
//   enabled          yes | no
