// Code generated by ikuai-api/codegen. DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	"net/url"
	"strconv"
	"strings"

	ikuaiapi "github.com/zy84338719/ikuai-api"
)

// V4Endpoint is a re-export of ikuaiapi.V4Endpoint so generated
// service files don't need to know the parent package layout.
type V4Endpoint = ikuaiapi.V4Endpoint

// Endpoints returns the full v4 catalog. It is provided as a helper for
// callers that want to discover the API at runtime.
func Endpoints() []V4Endpoint {
	return ikuaiapi.V4EndpointCatalog
}

// extractRowID parses the synthetic envelope emitted by Create responses
// ({"message": "...", "rowid": N}) and returns the rowid.
func extractRowID(raw json.RawMessage) (int64, error) {
	var env struct {
		RowID json.RawMessage `json:"rowid"`
	}
	if err := json.Unmarshal(raw, &env); err != nil || len(env.RowID) == 0 {
		return 0, nil
	}
	if v, err := strconv.ParseInt(string(env.RowID), 10, 64); err == nil {
		return v, nil
	}
	// Fall back to unmarshalling as a JSON number.
	var n json.Number
	if err := json.Unmarshal(env.RowID, &n); err != nil {
		return 0, nil
	}
	return n.Int64()
}

// APIClient is the typed v4 entry point. Construct it with NewAPIClient
// and call any of the per-group service accessors.
type APIClient struct {
	client        *ikuaiapi.Client
	svcAdvanced   *AdvancedService
	svcAuth       *AuthService
	svcInterfaces *InterfacesService
	svcLog        *LogService
	svcMonitoring *MonitoringService
	svcNetwork    *NetworkService
	svcObjects    *ObjectsService
	svcRouting    *RoutingService
	svcSecurity   *SecurityService
	svcSystem     *SystemService
	svcVpn        *VpnService
	svcWireless   *WirelessService
}

// NewAPIClient wires every group service to the supplied client.
func NewAPIClient(client *ikuaiapi.Client) *APIClient {
	return &APIClient{client: client,
		svcAdvanced:   &AdvancedService{client: client},
		svcAuth:       &AuthService{client: client},
		svcInterfaces: &InterfacesService{client: client},
		svcLog:        &LogService{client: client},
		svcMonitoring: &MonitoringService{client: client},
		svcNetwork:    &NetworkService{client: client},
		svcObjects:    &ObjectsService{client: client},
		svcRouting:    &RoutingService{client: client},
		svcSecurity:   &SecurityService{client: client},
		svcSystem:     &SystemService{client: client},
		svcVpn:        &VpnService{client: client},
		svcWireless:   &WirelessService{client: client},
	}
}

// Client returns the underlying ikuaiapi.Client. Use it for raw,
// catalog-driven calls when a typed helper does not exist yet.
func (a *APIClient) Client() *ikuaiapi.Client { return a.client }

func (a *APIClient) Advanced() *AdvancedService { return a.svcAdvanced }

func (a *APIClient) Auth() *AuthService { return a.svcAuth }

func (a *APIClient) Interfaces() *InterfacesService { return a.svcInterfaces }

func (a *APIClient) Log() *LogService { return a.svcLog }

func (a *APIClient) Monitoring() *MonitoringService { return a.svcMonitoring }

func (a *APIClient) Network() *NetworkService { return a.svcNetwork }

func (a *APIClient) Objects() *ObjectsService { return a.svcObjects }

func (a *APIClient) Routing() *RoutingService { return a.svcRouting }

func (a *APIClient) Security() *SecurityService { return a.svcSecurity }

func (a *APIClient) System() *SystemService { return a.svcSystem }

func (a *APIClient) Vpn() *VpnService { return a.svcVpn }

func (a *APIClient) Wireless() *WirelessService { return a.svcWireless }

// Call is the lowest-level escape hatch. It resolves a (group, name)
// pair from the catalog and dispatches the request using method,
// path, optional query params and optional JSON body. group is an
// optional sanity check; pass "" to look up by name only.
func (a *APIClient) Call(ctx context.Context, group, name, method string, body any, params map[string]string) (json.RawMessage, error) {
	ep, ok := ikuaiapi.V4EndpointByName(name)
	if !ok || (group != "" && ep.Group != group) {
		// Some names live under more than one group (e.g. "system")
		// so fall back to the explicit (group, name) lookup.
		if group != "" {
			if ep2, ok2 := ikuaiapi.V4EndpointByGroupName(group, name); ok2 {
				ep = ep2
			} else {
				return nil, &ikuaiapi.APIError{Message: "endpoint not found: " + group + "/" + name}
			}
		} else {
			return nil, &ikuaiapi.APIError{Message: "endpoint not found: " + name}
		}
	}
	switch method {
	case "GET":
		return a.client.Get(ctx, ep.Path, params)
	case "POST":
		return a.client.Post(ctx, ep.Path, body)
	case "PUT":
		return a.client.Put(ctx, ep.Path, body)
	case "PATCH":
		return a.client.Patch(ctx, ep.Path, body)
	case "DELETE":
		delURL := ep.Path
		if len(params) > 0 {
			sep := "?"
			if strings.Contains(ep.Path, "?") {
				sep = "&"
			}
			delURL = ep.Path + sep + a.client.FormatQuery(params)
		}
		return a.client.Delete(ctx, delURL, body)
	default:
		return nil, &ikuaiapi.APIError{Message: "unsupported method: " + method}
	}
}

// PageInfo mirrors the pagination metadata iKuai returns with list
// endpoints. It is exposed so callers can drive follow-up pages
// without having to declare a local struct.
type PageInfo struct {
	Page     int `json:"page"`
	PageSize int `json:"page_size"`
	Total    int `json:"total"`
}

// FormatURLValues is exposed for callers that build query strings
// by hand. It returns an empty string for a nil/empty map.
func FormatURLValues(q map[string]string) string {
	if len(q) == 0 {
		return ""
	}
	return urlEncode(q)
}

func urlEncode(q map[string]string) string {
	uv := make(url.Values)
	for k, v := range q {
		uv.Set(k, v)
	}
	return uv.Encode()
}
