// Code generated by ikuai-api/codegen. DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	ikuaiapi "github.com/zy84338719/ikuai-api"
	"strconv"
)

// RoutingService is the typed v4 entry point for the "routing" group.
// Method names follow the catalog Name field (CamelCased); the
// underlying HTTP verb and path are documented above each method.
type RoutingService struct {
	client *ikuaiapi.Client
}

// PathRouting is the v4 catalog table for this group; it is exported so
// callers can iterate endpoints or build dynamic requests.
var PathRouting = pathGroupRouting()

func pathGroupRouting() []V4Endpoint {
	src := ikuaiapi.V4EndpointCatalog
	out := make([]V4Endpoint, 0, 16)
	for _, ep := range src {
		if ep.Group == "routing" {
			out = append(out, ep)
		}
	}
	return out
}

// RoutingAppProtocols wraps routing app-protocols.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /routing/app-protocols
//
// Use ListRoutingAppProtocols(ctx, opts...) for paginated reads.
// RoutingAppProtocolsListOptions configures paginated reads of RoutingAppProtocols.
type RoutingAppProtocolsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *RoutingAppProtocolsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListRoutingAppProtocols lists items at /routing/app-protocols.
func (s *RoutingService) ListRoutingAppProtocols(ctx context.Context, opts *RoutingAppProtocolsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/routing/app-protocols", opts.query())
}

// GetRoutingAppProtocols fetches one item at /routing/app-protocols.
func (s *RoutingService) GetRoutingAppProtocols(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/routing/app-protocols", q)
}

// CreateRoutingAppProtocols posts a new item to /routing/app-protocols. The router returns a rowid on
// success which is propagated to the caller.
func (s *RoutingService) CreateRoutingAppProtocols(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/routing/app-protocols", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateRoutingAppProtocols replaces the resource at /routing/app-protocols.
func (s *RoutingService) UpdateRoutingAppProtocols(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/routing/app-protocols", body)
	return err
}

// PatchRoutingAppProtocols partial-updates the resource at /routing/app-protocols.
func (s *RoutingService) PatchRoutingAppProtocols(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/routing/app-protocols", body)
	return err
}

// DeleteRoutingAppProtocols removes the resource at /routing/app-protocols.
func (s *RoutingService) DeleteRoutingAppProtocols(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/routing/app-protocols", map[string]any{"id": id})
	return err
}

// RoutingDomainRules wraps routing domain-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /routing/domain-rules
//
// Use ListRoutingDomainRules(ctx, opts...) for paginated reads.
// RoutingDomainRulesListOptions configures paginated reads of RoutingDomainRules.
type RoutingDomainRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *RoutingDomainRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListRoutingDomainRules lists items at /routing/domain-rules.
func (s *RoutingService) ListRoutingDomainRules(ctx context.Context, opts *RoutingDomainRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/routing/domain-rules", opts.query())
}

// GetRoutingDomainRules fetches one item at /routing/domain-rules.
func (s *RoutingService) GetRoutingDomainRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/routing/domain-rules", q)
}

// CreateRoutingDomainRules posts a new item to /routing/domain-rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *RoutingService) CreateRoutingDomainRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/routing/domain-rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateRoutingDomainRules replaces the resource at /routing/domain-rules.
func (s *RoutingService) UpdateRoutingDomainRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/routing/domain-rules", body)
	return err
}

// PatchRoutingDomainRules partial-updates the resource at /routing/domain-rules.
func (s *RoutingService) PatchRoutingDomainRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/routing/domain-rules", body)
	return err
}

// DeleteRoutingDomainRules removes the resource at /routing/domain-rules.
func (s *RoutingService) DeleteRoutingDomainRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/routing/domain-rules", map[string]any{"id": id})
	return err
}

// RoutingFiveTupleRules wraps routing five-tuple-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /routing/five-tuple-rules
//
// Use ListRoutingFiveTupleRules(ctx, opts...) for paginated reads.
// RoutingFiveTupleRulesListOptions configures paginated reads of RoutingFiveTupleRules.
type RoutingFiveTupleRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *RoutingFiveTupleRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListRoutingFiveTupleRules lists items at /routing/five-tuple-rules.
func (s *RoutingService) ListRoutingFiveTupleRules(ctx context.Context, opts *RoutingFiveTupleRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/routing/five-tuple-rules", opts.query())
}

// GetRoutingFiveTupleRules fetches one item at /routing/five-tuple-rules.
func (s *RoutingService) GetRoutingFiveTupleRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/routing/five-tuple-rules", q)
}

// CreateRoutingFiveTupleRules posts a new item to /routing/five-tuple-rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *RoutingService) CreateRoutingFiveTupleRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/routing/five-tuple-rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateRoutingFiveTupleRules replaces the resource at /routing/five-tuple-rules.
func (s *RoutingService) UpdateRoutingFiveTupleRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/routing/five-tuple-rules", body)
	return err
}

// PatchRoutingFiveTupleRules partial-updates the resource at /routing/five-tuple-rules.
func (s *RoutingService) PatchRoutingFiveTupleRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/routing/five-tuple-rules", body)
	return err
}

// DeleteRoutingFiveTupleRules removes the resource at /routing/five-tuple-rules.
func (s *RoutingService) DeleteRoutingFiveTupleRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/routing/five-tuple-rules", map[string]any{"id": id})
	return err
}

// RoutingLoadBalanceRules wraps routing load-balance-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /routing/load-balance-rules
//
// Use ListRoutingLoadBalanceRules(ctx, opts...) for paginated reads.
// RoutingLoadBalanceRulesListOptions configures paginated reads of RoutingLoadBalanceRules.
type RoutingLoadBalanceRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *RoutingLoadBalanceRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListRoutingLoadBalanceRules lists items at /routing/load-balance-rules.
func (s *RoutingService) ListRoutingLoadBalanceRules(ctx context.Context, opts *RoutingLoadBalanceRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/routing/load-balance-rules", opts.query())
}

// GetRoutingLoadBalanceRules fetches one item at /routing/load-balance-rules.
func (s *RoutingService) GetRoutingLoadBalanceRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/routing/load-balance-rules", q)
}

// CreateRoutingLoadBalanceRules posts a new item to /routing/load-balance-rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *RoutingService) CreateRoutingLoadBalanceRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/routing/load-balance-rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateRoutingLoadBalanceRules replaces the resource at /routing/load-balance-rules.
func (s *RoutingService) UpdateRoutingLoadBalanceRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/routing/load-balance-rules", body)
	return err
}

// PatchRoutingLoadBalanceRules partial-updates the resource at /routing/load-balance-rules.
func (s *RoutingService) PatchRoutingLoadBalanceRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/routing/load-balance-rules", body)
	return err
}

// DeleteRoutingLoadBalanceRules removes the resource at /routing/load-balance-rules.
func (s *RoutingService) DeleteRoutingLoadBalanceRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/routing/load-balance-rules", map[string]any{"id": id})
	return err
}

// RoutingStaticRoutes wraps routing static-routes.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /routing/static-routes
//
// Use ListRoutingStaticRoutes(ctx, opts...) for paginated reads.
// RoutingStaticRoutesListOptions configures paginated reads of RoutingStaticRoutes.
type RoutingStaticRoutesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *RoutingStaticRoutesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListRoutingStaticRoutes lists items at /routing/static-routes.
func (s *RoutingService) ListRoutingStaticRoutes(ctx context.Context, opts *RoutingStaticRoutesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/routing/static-routes", opts.query())
}

// GetRoutingStaticRoutes fetches one item at /routing/static-routes.
func (s *RoutingService) GetRoutingStaticRoutes(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/routing/static-routes", q)
}

// CreateRoutingStaticRoutes posts a new item to /routing/static-routes. The router returns a rowid on
// success which is propagated to the caller.
func (s *RoutingService) CreateRoutingStaticRoutes(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/routing/static-routes", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateRoutingStaticRoutes replaces the resource at /routing/static-routes.
func (s *RoutingService) UpdateRoutingStaticRoutes(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/routing/static-routes", body)
	return err
}

// PatchRoutingStaticRoutes partial-updates the resource at /routing/static-routes.
func (s *RoutingService) PatchRoutingStaticRoutes(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/routing/static-routes", body)
	return err
}

// DeleteRoutingStaticRoutes removes the resource at /routing/static-routes.
func (s *RoutingService) DeleteRoutingStaticRoutes(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/routing/static-routes", map[string]any{"id": id})
	return err
}

// RoutingUpdown wraps routing updown.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /routing/updown
//
// Use ListRoutingUpdown(ctx, opts...) for paginated reads.
// RoutingUpdownListOptions configures paginated reads of RoutingUpdown.
type RoutingUpdownListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *RoutingUpdownListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListRoutingUpdown lists items at /routing/updown.
func (s *RoutingService) ListRoutingUpdown(ctx context.Context, opts *RoutingUpdownListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/routing/updown", opts.query())
}

// GetRoutingUpdown fetches one item at /routing/updown.
func (s *RoutingService) GetRoutingUpdown(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/routing/updown", q)
}

// CreateRoutingUpdown posts a new item to /routing/updown. The router returns a rowid on
// success which is propagated to the caller.
func (s *RoutingService) CreateRoutingUpdown(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/routing/updown", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateRoutingUpdown replaces the resource at /routing/updown.
func (s *RoutingService) UpdateRoutingUpdown(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/routing/updown", body)
	return err
}

// PatchRoutingUpdown partial-updates the resource at /routing/updown.
func (s *RoutingService) PatchRoutingUpdown(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/routing/updown", body)
	return err
}

// DeleteRoutingUpdown removes the resource at /routing/updown.
func (s *RoutingService) DeleteRoutingUpdown(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/routing/updown", map[string]any{"id": id})
	return err
}
