// Code generated by ikuai-api/codegen. DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	ikuaiapi "github.com/zy84338719/ikuai-api"
	"strconv"
)

// SecurityService is the typed v4 entry point for the "security" group.
// Method names follow the catalog Name field (CamelCased); the
// underlying HTTP verb and path are documented above each method.
type SecurityService struct {
	client *ikuaiapi.Client
}

// PathSecurity is the v4 catalog table for this group; it is exported so
// callers can iterate endpoints or build dynamic requests.
var PathSecurity = pathGroupSecurity()

func pathGroupSecurity() []V4Endpoint {
	src := ikuaiapi.V4EndpointCatalog
	out := make([]V4Endpoint, 0, 16)
	for _, ep := range src {
		if ep.Group == "security" {
			out = append(out, ep)
		}
	}
	return out
}

// SecurityAclRules wraps security acl-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /security/acl-rules
//
// Use ListSecurityAclRules(ctx, opts...) for paginated reads.
// SecurityAclRulesListOptions configures paginated reads of SecurityAclRules.
type SecurityAclRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SecurityAclRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSecurityAclRules lists items at /security/acl-rules.
func (s *SecurityService) ListSecurityAclRules(ctx context.Context, opts *SecurityAclRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/security/acl-rules", opts.query())
}

// GetSecurityAclRules fetches one item at /security/acl-rules.
func (s *SecurityService) GetSecurityAclRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/security/acl-rules", q)
}

// CreateSecurityAclRules posts a new item to /security/acl-rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *SecurityService) CreateSecurityAclRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/security/acl-rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSecurityAclRules replaces the resource at /security/acl-rules.
func (s *SecurityService) UpdateSecurityAclRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/security/acl-rules", body)
	return err
}

// PatchSecurityAclRules partial-updates the resource at /security/acl-rules.
func (s *SecurityService) PatchSecurityAclRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/security/acl-rules", body)
	return err
}

// DeleteSecurityAclRules removes the resource at /security/acl-rules.
func (s *SecurityService) DeleteSecurityAclRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/security/acl-rules", map[string]any{"id": id})
	return err
}

// SecurityAdvancedConfig wraps security advanced-config.
//
// Methods: GET, PUT
//
// Path: /security/advanced/config
//
// Use ListSecurityAdvancedConfig(ctx, opts...) for paginated reads.
// SecurityAdvancedConfigListOptions configures paginated reads of SecurityAdvancedConfig.
type SecurityAdvancedConfigListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SecurityAdvancedConfigListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSecurityAdvancedConfig lists items at /security/advanced/config.
func (s *SecurityService) ListSecurityAdvancedConfig(ctx context.Context, opts *SecurityAdvancedConfigListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/security/advanced/config", opts.query())
}

// GetSecurityAdvancedConfig fetches one item at /security/advanced/config.
func (s *SecurityService) GetSecurityAdvancedConfig(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/security/advanced/config", q)
}

// UpdateSecurityAdvancedConfig replaces the resource at /security/advanced/config.
func (s *SecurityService) UpdateSecurityAdvancedConfig(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/security/advanced/config", body)
	return err
}

// SecurityAppProtocolsProfessionalRules wraps security app-protocols-professional-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /security/app-protocols/professional/rules
//
// Use ListSecurityAppProtocolsProfessionalRules(ctx, opts...) for paginated reads.
// SecurityAppProtocolsProfessionalRulesListOptions configures paginated reads of SecurityAppProtocolsProfessionalRules.
type SecurityAppProtocolsProfessionalRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SecurityAppProtocolsProfessionalRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSecurityAppProtocolsProfessionalRules lists items at /security/app-protocols/professional/rules.
func (s *SecurityService) ListSecurityAppProtocolsProfessionalRules(ctx context.Context, opts *SecurityAppProtocolsProfessionalRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/security/app-protocols/professional/rules", opts.query())
}

// GetSecurityAppProtocolsProfessionalRules fetches one item at /security/app-protocols/professional/rules.
func (s *SecurityService) GetSecurityAppProtocolsProfessionalRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/security/app-protocols/professional/rules", q)
}

// CreateSecurityAppProtocolsProfessionalRules posts a new item to /security/app-protocols/professional/rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *SecurityService) CreateSecurityAppProtocolsProfessionalRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/security/app-protocols/professional/rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSecurityAppProtocolsProfessionalRules replaces the resource at /security/app-protocols/professional/rules.
func (s *SecurityService) UpdateSecurityAppProtocolsProfessionalRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/security/app-protocols/professional/rules", body)
	return err
}

// PatchSecurityAppProtocolsProfessionalRules partial-updates the resource at /security/app-protocols/professional/rules.
func (s *SecurityService) PatchSecurityAppProtocolsProfessionalRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/security/app-protocols/professional/rules", body)
	return err
}

// DeleteSecurityAppProtocolsProfessionalRules removes the resource at /security/app-protocols/professional/rules.
func (s *SecurityService) DeleteSecurityAppProtocolsProfessionalRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/security/app-protocols/professional/rules", map[string]any{"id": id})
	return err
}

// SecurityDomainBlacklistRules wraps security domain-blacklist-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /security/domain-blacklist/rules
//
// Use ListSecurityDomainBlacklistRules(ctx, opts...) for paginated reads.
// SecurityDomainBlacklistRulesListOptions configures paginated reads of SecurityDomainBlacklistRules.
type SecurityDomainBlacklistRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SecurityDomainBlacklistRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSecurityDomainBlacklistRules lists items at /security/domain-blacklist/rules.
func (s *SecurityService) ListSecurityDomainBlacklistRules(ctx context.Context, opts *SecurityDomainBlacklistRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/security/domain-blacklist/rules", opts.query())
}

// GetSecurityDomainBlacklistRules fetches one item at /security/domain-blacklist/rules.
func (s *SecurityService) GetSecurityDomainBlacklistRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/security/domain-blacklist/rules", q)
}

// CreateSecurityDomainBlacklistRules posts a new item to /security/domain-blacklist/rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *SecurityService) CreateSecurityDomainBlacklistRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/security/domain-blacklist/rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSecurityDomainBlacklistRules replaces the resource at /security/domain-blacklist/rules.
func (s *SecurityService) UpdateSecurityDomainBlacklistRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/security/domain-blacklist/rules", body)
	return err
}

// PatchSecurityDomainBlacklistRules partial-updates the resource at /security/domain-blacklist/rules.
func (s *SecurityService) PatchSecurityDomainBlacklistRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/security/domain-blacklist/rules", body)
	return err
}

// DeleteSecurityDomainBlacklistRules removes the resource at /security/domain-blacklist/rules.
func (s *SecurityService) DeleteSecurityDomainBlacklistRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/security/domain-blacklist/rules", map[string]any{"id": id})
	return err
}

// SecurityMacMode wraps security mac-mode.
//
// Methods: GET, PUT
//
// Path: /security/mac-mode
//
// Use ListSecurityMacMode(ctx, opts...) for paginated reads.
// SecurityMacModeListOptions configures paginated reads of SecurityMacMode.
type SecurityMacModeListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SecurityMacModeListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSecurityMacMode lists items at /security/mac-mode.
func (s *SecurityService) ListSecurityMacMode(ctx context.Context, opts *SecurityMacModeListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/security/mac-mode", opts.query())
}

// GetSecurityMacMode fetches one item at /security/mac-mode.
func (s *SecurityService) GetSecurityMacMode(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/security/mac-mode", q)
}

// UpdateSecurityMacMode replaces the resource at /security/mac-mode.
func (s *SecurityService) UpdateSecurityMacMode(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/security/mac-mode", body)
	return err
}

// SecurityMacRules wraps security mac-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /security/mac-rules
//
// Use ListSecurityMacRules(ctx, opts...) for paginated reads.
// SecurityMacRulesListOptions configures paginated reads of SecurityMacRules.
type SecurityMacRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SecurityMacRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSecurityMacRules lists items at /security/mac-rules.
func (s *SecurityService) ListSecurityMacRules(ctx context.Context, opts *SecurityMacRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/security/mac-rules", opts.query())
}

// GetSecurityMacRules fetches one item at /security/mac-rules.
func (s *SecurityService) GetSecurityMacRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/security/mac-rules", q)
}

// CreateSecurityMacRules posts a new item to /security/mac-rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *SecurityService) CreateSecurityMacRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/security/mac-rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSecurityMacRules replaces the resource at /security/mac-rules.
func (s *SecurityService) UpdateSecurityMacRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/security/mac-rules", body)
	return err
}

// PatchSecurityMacRules partial-updates the resource at /security/mac-rules.
func (s *SecurityService) PatchSecurityMacRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/security/mac-rules", body)
	return err
}

// DeleteSecurityMacRules removes the resource at /security/mac-rules.
func (s *SecurityService) DeleteSecurityMacRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/security/mac-rules", map[string]any{"id": id})
	return err
}

// SecurityPeerconnRules wraps security peerconn-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /security/peerconn/rules
//
// Use ListSecurityPeerconnRules(ctx, opts...) for paginated reads.
// SecurityPeerconnRulesListOptions configures paginated reads of SecurityPeerconnRules.
type SecurityPeerconnRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SecurityPeerconnRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSecurityPeerconnRules lists items at /security/peerconn/rules.
func (s *SecurityService) ListSecurityPeerconnRules(ctx context.Context, opts *SecurityPeerconnRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/security/peerconn/rules", opts.query())
}

// GetSecurityPeerconnRules fetches one item at /security/peerconn/rules.
func (s *SecurityService) GetSecurityPeerconnRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/security/peerconn/rules", q)
}

// CreateSecurityPeerconnRules posts a new item to /security/peerconn/rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *SecurityService) CreateSecurityPeerconnRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/security/peerconn/rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSecurityPeerconnRules replaces the resource at /security/peerconn/rules.
func (s *SecurityService) UpdateSecurityPeerconnRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/security/peerconn/rules", body)
	return err
}

// PatchSecurityPeerconnRules partial-updates the resource at /security/peerconn/rules.
func (s *SecurityService) PatchSecurityPeerconnRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/security/peerconn/rules", body)
	return err
}

// DeleteSecurityPeerconnRules removes the resource at /security/peerconn/rules.
func (s *SecurityService) DeleteSecurityPeerconnRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/security/peerconn/rules", map[string]any{"id": id})
	return err
}

// SecuritySecondaryRouteConfig wraps security secondary-route-config.
//
// Methods: GET, PUT
//
// Path: /security/secondary-route/config
//
// Use ListSecuritySecondaryRouteConfig(ctx, opts...) for paginated reads.
// SecuritySecondaryRouteConfigListOptions configures paginated reads of SecuritySecondaryRouteConfig.
type SecuritySecondaryRouteConfigListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SecuritySecondaryRouteConfigListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSecuritySecondaryRouteConfig lists items at /security/secondary-route/config.
func (s *SecurityService) ListSecuritySecondaryRouteConfig(ctx context.Context, opts *SecuritySecondaryRouteConfigListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/security/secondary-route/config", opts.query())
}

// GetSecuritySecondaryRouteConfig fetches one item at /security/secondary-route/config.
func (s *SecurityService) GetSecuritySecondaryRouteConfig(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/security/secondary-route/config", q)
}

// UpdateSecuritySecondaryRouteConfig replaces the resource at /security/secondary-route/config.
func (s *SecurityService) UpdateSecuritySecondaryRouteConfig(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/security/secondary-route/config", body)
	return err
}

// SecurityTerminals wraps security terminals.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /security/terminals
//
// Use ListSecurityTerminals(ctx, opts...) for paginated reads.
// SecurityTerminalsListOptions configures paginated reads of SecurityTerminals.
type SecurityTerminalsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SecurityTerminalsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSecurityTerminals lists items at /security/terminals.
func (s *SecurityService) ListSecurityTerminals(ctx context.Context, opts *SecurityTerminalsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/security/terminals", opts.query())
}

// GetSecurityTerminals fetches one item at /security/terminals.
func (s *SecurityService) GetSecurityTerminals(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/security/terminals", q)
}

// CreateSecurityTerminals posts a new item to /security/terminals. The router returns a rowid on
// success which is propagated to the caller.
func (s *SecurityService) CreateSecurityTerminals(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/security/terminals", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSecurityTerminals replaces the resource at /security/terminals.
func (s *SecurityService) UpdateSecurityTerminals(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/security/terminals", body)
	return err
}

// PatchSecurityTerminals partial-updates the resource at /security/terminals.
func (s *SecurityService) PatchSecurityTerminals(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/security/terminals", body)
	return err
}

// DeleteSecurityTerminals removes the resource at /security/terminals.
func (s *SecurityService) DeleteSecurityTerminals(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/security/terminals", map[string]any{"id": id})
	return err
}

// SecurityUrlBlackRules wraps security url-black-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /security/url-black/rules
//
// Use ListSecurityUrlBlackRules(ctx, opts...) for paginated reads.
// SecurityUrlBlackRulesListOptions configures paginated reads of SecurityUrlBlackRules.
type SecurityUrlBlackRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SecurityUrlBlackRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSecurityUrlBlackRules lists items at /security/url-black/rules.
func (s *SecurityService) ListSecurityUrlBlackRules(ctx context.Context, opts *SecurityUrlBlackRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/security/url-black/rules", opts.query())
}

// GetSecurityUrlBlackRules fetches one item at /security/url-black/rules.
func (s *SecurityService) GetSecurityUrlBlackRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/security/url-black/rules", q)
}

// CreateSecurityUrlBlackRules posts a new item to /security/url-black/rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *SecurityService) CreateSecurityUrlBlackRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/security/url-black/rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSecurityUrlBlackRules replaces the resource at /security/url-black/rules.
func (s *SecurityService) UpdateSecurityUrlBlackRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/security/url-black/rules", body)
	return err
}

// PatchSecurityUrlBlackRules partial-updates the resource at /security/url-black/rules.
func (s *SecurityService) PatchSecurityUrlBlackRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/security/url-black/rules", body)
	return err
}

// DeleteSecurityUrlBlackRules removes the resource at /security/url-black/rules.
func (s *SecurityService) DeleteSecurityUrlBlackRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/security/url-black/rules", map[string]any{"id": id})
	return err
}

// SecurityUrlKeywordsRules wraps security url-keywords-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /security/url-keywords/rules
//
// Use ListSecurityUrlKeywordsRules(ctx, opts...) for paginated reads.
// SecurityUrlKeywordsRulesListOptions configures paginated reads of SecurityUrlKeywordsRules.
type SecurityUrlKeywordsRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SecurityUrlKeywordsRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSecurityUrlKeywordsRules lists items at /security/url-keywords/rules.
func (s *SecurityService) ListSecurityUrlKeywordsRules(ctx context.Context, opts *SecurityUrlKeywordsRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/security/url-keywords/rules", opts.query())
}

// GetSecurityUrlKeywordsRules fetches one item at /security/url-keywords/rules.
func (s *SecurityService) GetSecurityUrlKeywordsRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/security/url-keywords/rules", q)
}

// CreateSecurityUrlKeywordsRules posts a new item to /security/url-keywords/rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *SecurityService) CreateSecurityUrlKeywordsRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/security/url-keywords/rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSecurityUrlKeywordsRules replaces the resource at /security/url-keywords/rules.
func (s *SecurityService) UpdateSecurityUrlKeywordsRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/security/url-keywords/rules", body)
	return err
}

// PatchSecurityUrlKeywordsRules partial-updates the resource at /security/url-keywords/rules.
func (s *SecurityService) PatchSecurityUrlKeywordsRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/security/url-keywords/rules", body)
	return err
}

// DeleteSecurityUrlKeywordsRules removes the resource at /security/url-keywords/rules.
func (s *SecurityService) DeleteSecurityUrlKeywordsRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/security/url-keywords/rules", map[string]any{"id": id})
	return err
}

// SecurityUrlRedirectRules wraps security url-redirect-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /security/url-redirect/rules
//
// Use ListSecurityUrlRedirectRules(ctx, opts...) for paginated reads.
// SecurityUrlRedirectRulesListOptions configures paginated reads of SecurityUrlRedirectRules.
type SecurityUrlRedirectRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SecurityUrlRedirectRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSecurityUrlRedirectRules lists items at /security/url-redirect/rules.
func (s *SecurityService) ListSecurityUrlRedirectRules(ctx context.Context, opts *SecurityUrlRedirectRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/security/url-redirect/rules", opts.query())
}

// GetSecurityUrlRedirectRules fetches one item at /security/url-redirect/rules.
func (s *SecurityService) GetSecurityUrlRedirectRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/security/url-redirect/rules", q)
}

// CreateSecurityUrlRedirectRules posts a new item to /security/url-redirect/rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *SecurityService) CreateSecurityUrlRedirectRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/security/url-redirect/rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSecurityUrlRedirectRules replaces the resource at /security/url-redirect/rules.
func (s *SecurityService) UpdateSecurityUrlRedirectRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/security/url-redirect/rules", body)
	return err
}

// PatchSecurityUrlRedirectRules partial-updates the resource at /security/url-redirect/rules.
func (s *SecurityService) PatchSecurityUrlRedirectRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/security/url-redirect/rules", body)
	return err
}

// DeleteSecurityUrlRedirectRules removes the resource at /security/url-redirect/rules.
func (s *SecurityService) DeleteSecurityUrlRedirectRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/security/url-redirect/rules", map[string]any{"id": id})
	return err
}

// SecurityUrlReplaceRules wraps security url-replace-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /security/url-replace/rules
//
// Use ListSecurityUrlReplaceRules(ctx, opts...) for paginated reads.
// SecurityUrlReplaceRulesListOptions configures paginated reads of SecurityUrlReplaceRules.
type SecurityUrlReplaceRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SecurityUrlReplaceRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSecurityUrlReplaceRules lists items at /security/url-replace/rules.
func (s *SecurityService) ListSecurityUrlReplaceRules(ctx context.Context, opts *SecurityUrlReplaceRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/security/url-replace/rules", opts.query())
}

// GetSecurityUrlReplaceRules fetches one item at /security/url-replace/rules.
func (s *SecurityService) GetSecurityUrlReplaceRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/security/url-replace/rules", q)
}

// CreateSecurityUrlReplaceRules posts a new item to /security/url-replace/rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *SecurityService) CreateSecurityUrlReplaceRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/security/url-replace/rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSecurityUrlReplaceRules replaces the resource at /security/url-replace/rules.
func (s *SecurityService) UpdateSecurityUrlReplaceRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/security/url-replace/rules", body)
	return err
}

// PatchSecurityUrlReplaceRules partial-updates the resource at /security/url-replace/rules.
func (s *SecurityService) PatchSecurityUrlReplaceRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/security/url-replace/rules", body)
	return err
}

// DeleteSecurityUrlReplaceRules removes the resource at /security/url-replace/rules.
func (s *SecurityService) DeleteSecurityUrlReplaceRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/security/url-replace/rules", map[string]any{"id": id})
	return err
}
