// Code generated by ikuai-api/codegen. DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	ikuaiapi "github.com/zy84338719/ikuai-api"
	"strconv"
)

// SystemService is the typed v4 entry point for the "system" group.
// Method names follow the catalog Name field (CamelCased); the
// underlying HTTP verb and path are documented above each method.
type SystemService struct {
	client *ikuaiapi.Client
}

// PathSystem is the v4 catalog table for this group; it is exported so
// callers can iterate endpoints or build dynamic requests.
var PathSystem = pathGroupSystem()

func pathGroupSystem() []V4Endpoint {
	src := ikuaiapi.V4EndpointCatalog
	out := make([]V4Endpoint, 0, 16)
	for _, ep := range src {
		if ep.Group == "system" {
			out = append(out, ep)
		}
	}
	return out
}

// SystemAcClients wraps system ac-clients.
//
// Methods: GET, POST, PUT, DELETE
//
// Path: /clients
//
// Use ListSystemAcClients(ctx, opts...) for paginated reads.
// SystemAcClientsListOptions configures paginated reads of SystemAcClients.
type SystemAcClientsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemAcClientsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemAcClients lists items at /clients.
func (s *SystemService) ListSystemAcClients(ctx context.Context, opts *SystemAcClientsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/clients", opts.query())
}

// GetSystemAcClients fetches one item at /clients.
func (s *SystemService) GetSystemAcClients(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/clients", q)
}

// CreateSystemAcClients posts a new item to /clients. The router returns a rowid on
// success which is propagated to the caller.
func (s *SystemService) CreateSystemAcClients(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/clients", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSystemAcClients replaces the resource at /clients.
func (s *SystemService) UpdateSystemAcClients(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/clients", body)
	return err
}

// DeleteSystemAcClients removes the resource at /clients.
func (s *SystemService) DeleteSystemAcClients(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/clients", map[string]any{"id": id})
	return err
}

// SystemAcPeers wraps system ac-peers.
//
// Methods: GET, POST, PUT, DELETE
//
// Path: /peers
//
// Use ListSystemAcPeers(ctx, opts...) for paginated reads.
// SystemAcPeersListOptions configures paginated reads of SystemAcPeers.
type SystemAcPeersListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemAcPeersListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemAcPeers lists items at /peers.
func (s *SystemService) ListSystemAcPeers(ctx context.Context, opts *SystemAcPeersListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/peers", opts.query())
}

// GetSystemAcPeers fetches one item at /peers.
func (s *SystemService) GetSystemAcPeers(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/peers", q)
}

// CreateSystemAcPeers posts a new item to /peers. The router returns a rowid on
// success which is propagated to the caller.
func (s *SystemService) CreateSystemAcPeers(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/peers", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSystemAcPeers replaces the resource at /peers.
func (s *SystemService) UpdateSystemAcPeers(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/peers", body)
	return err
}

// DeleteSystemAcPeers removes the resource at /peers.
func (s *SystemService) DeleteSystemAcPeers(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/peers", map[string]any{"id": id})
	return err
}

// SystemAcRef wraps system ac-ref.
//
// Methods: GET, POST, PUT, DELETE
//
// Path: /ref
//
// Use ListSystemAcRef(ctx, opts...) for paginated reads.
// SystemAcRefListOptions configures paginated reads of SystemAcRef.
type SystemAcRefListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemAcRefListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemAcRef lists items at /ref.
func (s *SystemService) ListSystemAcRef(ctx context.Context, opts *SystemAcRefListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/ref", opts.query())
}

// GetSystemAcRef fetches one item at /ref.
func (s *SystemService) GetSystemAcRef(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/ref", q)
}

// CreateSystemAcRef posts a new item to /ref. The router returns a rowid on
// success which is propagated to the caller.
func (s *SystemService) CreateSystemAcRef(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/ref", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSystemAcRef replaces the resource at /ref.
func (s *SystemService) UpdateSystemAcRef(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/ref", body)
	return err
}

// DeleteSystemAcRef removes the resource at /ref.
func (s *SystemService) DeleteSystemAcRef(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/ref", map[string]any{"id": id})
	return err
}

// SystemAcServices wraps system ac-services.
//
// Methods: GET, POST, PUT, DELETE
//
// Path: /services
//
// Use ListSystemAcServices(ctx, opts...) for paginated reads.
// SystemAcServicesListOptions configures paginated reads of SystemAcServices.
type SystemAcServicesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemAcServicesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemAcServices lists items at /services.
func (s *SystemService) ListSystemAcServices(ctx context.Context, opts *SystemAcServicesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/services", opts.query())
}

// GetSystemAcServices fetches one item at /services.
func (s *SystemService) GetSystemAcServices(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/services", q)
}

// CreateSystemAcServices posts a new item to /services. The router returns a rowid on
// success which is propagated to the caller.
func (s *SystemService) CreateSystemAcServices(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/services", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSystemAcServices replaces the resource at /services.
func (s *SystemService) UpdateSystemAcServices(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/services", body)
	return err
}

// DeleteSystemAcServices removes the resource at /services.
func (s *SystemService) DeleteSystemAcServices(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/services", map[string]any{"id": id})
	return err
}

// SystemAlg wraps system alg.
//
// Methods: GET, PUT
//
// Path: /system/alg
//
// Use ListSystemAlg(ctx, opts...) for paginated reads.
// SystemAlgListOptions configures paginated reads of SystemAlg.
type SystemAlgListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemAlgListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemAlg lists items at /system/alg.
func (s *SystemService) ListSystemAlg(ctx context.Context, opts *SystemAlgListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/alg", opts.query())
}

// GetSystemAlg fetches one item at /system/alg.
func (s *SystemService) GetSystemAlg(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/system/alg", q)
}

// UpdateSystemAlg replaces the resource at /system/alg.
func (s *SystemService) UpdateSystemAlg(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/system/alg", body)
	return err
}

// SystemBackup wraps system backup.
//
// Methods: GET, POST
//
// Path: /system/backup
//
// Use ListSystemBackup(ctx, opts...) for paginated reads.
// SystemBackupListOptions configures paginated reads of SystemBackup.
type SystemBackupListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemBackupListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemBackup lists items at /system/backup.
func (s *SystemService) ListSystemBackup(ctx context.Context, opts *SystemBackupListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/backup", opts.query())
}

// GetSystemBackup fetches one item at /system/backup.
func (s *SystemService) GetSystemBackup(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/system/backup", q)
}

// CreateSystemBackup posts a new item to /system/backup. The router returns a rowid on
// success which is propagated to the caller.
func (s *SystemService) CreateSystemBackup(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/system/backup", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// SystemBackupAuto wraps system backup-auto.
//
// Methods: GET, POST, PUT, DELETE
//
// Path: /system/backup-auto
//
// Use ListSystemBackupAuto(ctx, opts...) for paginated reads.
// SystemBackupAutoListOptions configures paginated reads of SystemBackupAuto.
type SystemBackupAutoListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemBackupAutoListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemBackupAuto lists items at /system/backup-auto.
func (s *SystemService) ListSystemBackupAuto(ctx context.Context, opts *SystemBackupAutoListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/backup-auto", opts.query())
}

// GetSystemBackupAuto fetches one item at /system/backup-auto.
func (s *SystemService) GetSystemBackupAuto(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/system/backup-auto", q)
}

// CreateSystemBackupAuto posts a new item to /system/backup-auto. The router returns a rowid on
// success which is propagated to the caller.
func (s *SystemService) CreateSystemBackupAuto(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/system/backup-auto", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSystemBackupAuto replaces the resource at /system/backup-auto.
func (s *SystemService) UpdateSystemBackupAuto(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/system/backup-auto", body)
	return err
}

// DeleteSystemBackupAuto removes the resource at /system/backup-auto.
func (s *SystemService) DeleteSystemBackupAuto(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/system/backup-auto", map[string]any{"id": id})
	return err
}

// SystemBackupRestore wraps system backup-restore.
//
// Methods: POST
//
// Path: /system/backup:restore
func (s *SystemService) DoSystemBackupRestore(ctx context.Context, body any) (json.RawMessage, error) {
	return s.client.Post(ctx, "/system/backup:restore", body)
}

// SystemBasicConfig wraps system basic-config.
//
// Methods: GET, PUT
//
// Path: /system/basic/config
//
// Use ListSystemBasicConfig(ctx, opts...) for paginated reads.
// SystemBasicConfigListOptions configures paginated reads of SystemBasicConfig.
type SystemBasicConfigListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemBasicConfigListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemBasicConfig lists items at /system/basic/config.
func (s *SystemService) ListSystemBasicConfig(ctx context.Context, opts *SystemBasicConfigListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/basic/config", opts.query())
}

// GetSystemBasicConfig fetches one item at /system/basic/config.
func (s *SystemService) GetSystemBasicConfig(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/system/basic/config", q)
}

// UpdateSystemBasicConfig replaces the resource at /system/basic/config.
func (s *SystemService) UpdateSystemBasicConfig(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/system/basic/config", body)
	return err
}

// SystemBasicNtpSync wraps system basic-ntp-sync.
//
// Methods: POST
//
// Path: /system/basic/ntp:sync
func (s *SystemService) DoSystemBasicNtpSync(ctx context.Context, body any) (json.RawMessage, error) {
	return s.client.Post(ctx, "/system/basic/ntp:sync", body)
}

// SystemCpufreq wraps system cpufreq.
//
// Methods: GET, PUT
//
// Path: /system/cpufreq
//
// Use ListSystemCpufreq(ctx, opts...) for paginated reads.
// SystemCpufreqListOptions configures paginated reads of SystemCpufreq.
type SystemCpufreqListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemCpufreqListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemCpufreq lists items at /system/cpufreq.
func (s *SystemService) ListSystemCpufreq(ctx context.Context, opts *SystemCpufreqListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/cpufreq", opts.query())
}

// GetSystemCpufreq fetches one item at /system/cpufreq.
func (s *SystemService) GetSystemCpufreq(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/system/cpufreq", q)
}

// UpdateSystemCpufreq replaces the resource at /system/cpufreq.
func (s *SystemService) UpdateSystemCpufreq(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/system/cpufreq", body)
	return err
}

// SystemCpufreqMode wraps system cpufreq-mode.
//
// Methods: PUT
//
// Path: /system/cpufreq/mode
// SystemCpufreqModeListOptions configures paginated reads of SystemCpufreqMode.
type SystemCpufreqModeListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemCpufreqModeListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// UpdateSystemCpufreqMode replaces the resource at /system/cpufreq/mode.
func (s *SystemService) UpdateSystemCpufreqMode(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/system/cpufreq/mode", body)
	return err
}

// SystemDisks wraps system disks.
//
// Methods: GET
//
// Path: /system/disks
//
// Use ListSystemDisks(ctx, opts...) for paginated reads.
func (s *SystemService) GetSystemDisks(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/disks", nil)
}

// SystemFiles wraps system files.
//
// Methods: GET
//
// Path: /system/files
//
// Use ListSystemFiles(ctx, opts...) for paginated reads.
func (s *SystemService) GetSystemFiles(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/files", nil)
}

// SystemKernelParams wraps system kernel-params.
//
// Methods: GET, PUT
//
// Path: /system/kernel-params
//
// Use ListSystemKernelParams(ctx, opts...) for paginated reads.
// SystemKernelParamsListOptions configures paginated reads of SystemKernelParams.
type SystemKernelParamsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemKernelParamsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemKernelParams lists items at /system/kernel-params.
func (s *SystemService) ListSystemKernelParams(ctx context.Context, opts *SystemKernelParamsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/kernel-params", opts.query())
}

// GetSystemKernelParams fetches one item at /system/kernel-params.
func (s *SystemService) GetSystemKernelParams(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/system/kernel-params", q)
}

// UpdateSystemKernelParams replaces the resource at /system/kernel-params.
func (s *SystemService) UpdateSystemKernelParams(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/system/kernel-params", body)
	return err
}

// SystemRebootSchedules wraps system reboot-schedules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /system/reboot-schedules
//
// Use ListSystemRebootSchedules(ctx, opts...) for paginated reads.
// SystemRebootSchedulesListOptions configures paginated reads of SystemRebootSchedules.
type SystemRebootSchedulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemRebootSchedulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemRebootSchedules lists items at /system/reboot-schedules.
func (s *SystemService) ListSystemRebootSchedules(ctx context.Context, opts *SystemRebootSchedulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/reboot-schedules", opts.query())
}

// GetSystemRebootSchedules fetches one item at /system/reboot-schedules.
func (s *SystemService) GetSystemRebootSchedules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/system/reboot-schedules", q)
}

// CreateSystemRebootSchedules posts a new item to /system/reboot-schedules. The router returns a rowid on
// success which is propagated to the caller.
func (s *SystemService) CreateSystemRebootSchedules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/system/reboot-schedules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSystemRebootSchedules replaces the resource at /system/reboot-schedules.
func (s *SystemService) UpdateSystemRebootSchedules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/system/reboot-schedules", body)
	return err
}

// PatchSystemRebootSchedules partial-updates the resource at /system/reboot-schedules.
func (s *SystemService) PatchSystemRebootSchedules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/system/reboot-schedules", body)
	return err
}

// DeleteSystemRebootSchedules removes the resource at /system/reboot-schedules.
func (s *SystemService) DeleteSystemRebootSchedules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/system/reboot-schedules", map[string]any{"id": id})
	return err
}

// SystemRemoteAccess wraps system remote-access.
//
// Methods: GET, PUT
//
// Path: /system/remote-access
//
// Use ListSystemRemoteAccess(ctx, opts...) for paginated reads.
// SystemRemoteAccessListOptions configures paginated reads of SystemRemoteAccess.
type SystemRemoteAccessListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemRemoteAccessListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemRemoteAccess lists items at /system/remote-access.
func (s *SystemService) ListSystemRemoteAccess(ctx context.Context, opts *SystemRemoteAccessListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/remote-access", opts.query())
}

// GetSystemRemoteAccess fetches one item at /system/remote-access.
func (s *SystemService) GetSystemRemoteAccess(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/system/remote-access", q)
}

// UpdateSystemRemoteAccess replaces the resource at /system/remote-access.
func (s *SystemService) UpdateSystemRemoteAccess(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/system/remote-access", body)
	return err
}

// SystemUpgrade wraps system upgrade.
//
// Methods: GET, POST
//
// Path: /system/upgrade
//
// Use ListSystemUpgrade(ctx, opts...) for paginated reads.
// SystemUpgradeListOptions configures paginated reads of SystemUpgrade.
type SystemUpgradeListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemUpgradeListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemUpgrade lists items at /system/upgrade.
func (s *SystemService) ListSystemUpgrade(ctx context.Context, opts *SystemUpgradeListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/upgrade", opts.query())
}

// GetSystemUpgrade fetches one item at /system/upgrade.
func (s *SystemService) GetSystemUpgrade(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/system/upgrade", q)
}

// CreateSystemUpgrade posts a new item to /system/upgrade. The router returns a rowid on
// success which is propagated to the caller.
func (s *SystemService) CreateSystemUpgrade(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/system/upgrade", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// SystemUpgradeCheck wraps system upgrade-check.
//
// Methods: POST
//
// Path: /system/upgrade:check
func (s *SystemService) DoSystemUpgradeCheck(ctx context.Context, body any) (json.RawMessage, error) {
	return s.client.Post(ctx, "/system/upgrade:check", body)
}

// SystemUpgradeStart wraps system upgrade-start.
//
// Methods: POST
//
// Path: /system/upgrade:start
func (s *SystemService) DoSystemUpgradeStart(ctx context.Context, body any) (json.RawMessage, error) {
	return s.client.Post(ctx, "/system/upgrade:start", body)
}

// SystemUpgradeStatus wraps system upgrade-status.
//
// Methods: GET
//
// Path: /system/upgrade:status
//
// Use ListSystemUpgradeStatus(ctx, opts...) for paginated reads.
func (s *SystemService) GetSystemUpgradeStatus(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/upgrade:status", nil)
}

// SystemVrrpConfig wraps system vrrp-config.
//
// Methods: GET, PUT
//
// Path: /system/vrrp/config
//
// Use ListSystemVrrpConfig(ctx, opts...) for paginated reads.
// SystemVrrpConfigListOptions configures paginated reads of SystemVrrpConfig.
type SystemVrrpConfigListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemVrrpConfigListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemVrrpConfig lists items at /system/vrrp/config.
func (s *SystemService) ListSystemVrrpConfig(ctx context.Context, opts *SystemVrrpConfigListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/vrrp/config", opts.query())
}

// GetSystemVrrpConfig fetches one item at /system/vrrp/config.
func (s *SystemService) GetSystemVrrpConfig(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/system/vrrp/config", q)
}

// UpdateSystemVrrpConfig replaces the resource at /system/vrrp/config.
func (s *SystemService) UpdateSystemVrrpConfig(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/system/vrrp/config", body)
	return err
}

// SystemVrrpStart wraps system vrrp-start.
//
// Methods: POST
//
// Path: /system/vrrp:start
func (s *SystemService) DoSystemVrrpStart(ctx context.Context, body any) (json.RawMessage, error) {
	return s.client.Post(ctx, "/system/vrrp:start", body)
}

// SystemVrrpStop wraps system vrrp-stop.
//
// Methods: POST
//
// Path: /system/vrrp:stop
func (s *SystemService) DoSystemVrrpStop(ctx context.Context, body any) (json.RawMessage, error) {
	return s.client.Post(ctx, "/system/vrrp:stop", body)
}

// SystemWebAdminAccounts wraps system web-admin-accounts.
//
// Methods: GET, POST, PUT, DELETE
//
// Path: /system/web-admin/accounts
//
// Use ListSystemWebAdminAccounts(ctx, opts...) for paginated reads.
// SystemWebAdminAccountsListOptions configures paginated reads of SystemWebAdminAccounts.
type SystemWebAdminAccountsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemWebAdminAccountsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemWebAdminAccounts lists items at /system/web-admin/accounts.
func (s *SystemService) ListSystemWebAdminAccounts(ctx context.Context, opts *SystemWebAdminAccountsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/web-admin/accounts", opts.query())
}

// GetSystemWebAdminAccounts fetches one item at /system/web-admin/accounts.
func (s *SystemService) GetSystemWebAdminAccounts(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/system/web-admin/accounts", q)
}

// CreateSystemWebAdminAccounts posts a new item to /system/web-admin/accounts. The router returns a rowid on
// success which is propagated to the caller.
func (s *SystemService) CreateSystemWebAdminAccounts(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/system/web-admin/accounts", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSystemWebAdminAccounts replaces the resource at /system/web-admin/accounts.
func (s *SystemService) UpdateSystemWebAdminAccounts(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/system/web-admin/accounts", body)
	return err
}

// DeleteSystemWebAdminAccounts removes the resource at /system/web-admin/accounts.
func (s *SystemService) DeleteSystemWebAdminAccounts(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/system/web-admin/accounts", map[string]any{"id": id})
	return err
}

// SystemWebAdminGroups wraps system web-admin-groups.
//
// Methods: GET, POST, PUT, DELETE
//
// Path: /system/web-admin/groups
//
// Use ListSystemWebAdminGroups(ctx, opts...) for paginated reads.
// SystemWebAdminGroupsListOptions configures paginated reads of SystemWebAdminGroups.
type SystemWebAdminGroupsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemWebAdminGroupsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListSystemWebAdminGroups lists items at /system/web-admin/groups.
func (s *SystemService) ListSystemWebAdminGroups(ctx context.Context, opts *SystemWebAdminGroupsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/web-admin/groups", opts.query())
}

// GetSystemWebAdminGroups fetches one item at /system/web-admin/groups.
func (s *SystemService) GetSystemWebAdminGroups(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/system/web-admin/groups", q)
}

// CreateSystemWebAdminGroups posts a new item to /system/web-admin/groups. The router returns a rowid on
// success which is propagated to the caller.
func (s *SystemService) CreateSystemWebAdminGroups(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/system/web-admin/groups", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateSystemWebAdminGroups replaces the resource at /system/web-admin/groups.
func (s *SystemService) UpdateSystemWebAdminGroups(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/system/web-admin/groups", body)
	return err
}

// DeleteSystemWebAdminGroups removes the resource at /system/web-admin/groups.
func (s *SystemService) DeleteSystemWebAdminGroups(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/system/web-admin/groups", map[string]any{"id": id})
	return err
}

// SystemWebAdminPassword wraps system web-admin-password.
//
// Methods: PUT
//
// Path: /system/web-admin/password
// SystemWebAdminPasswordListOptions configures paginated reads of SystemWebAdminPassword.
type SystemWebAdminPasswordListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *SystemWebAdminPasswordListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// UpdateSystemWebAdminPassword replaces the resource at /system/web-admin/password.
func (s *SystemService) UpdateSystemWebAdminPassword(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/system/web-admin/password", body)
	return err
}

// SystemWebAdminPasswordStatus wraps system web-admin-password-status.
//
// Methods: GET
//
// Path: /system/web-admin/password-status
//
// Use ListSystemWebAdminPasswordStatus(ctx, opts...) for paginated reads.
func (s *SystemService) GetSystemWebAdminPasswordStatus(ctx context.Context) (json.RawMessage, error) {
	return s.client.Get(ctx, "/system/web-admin/password-status", nil)
}
