// Code generated by ikuai-api/codegen. DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	"strconv"
	ikuaiapi "github.com/zy84338719/ikuai-api"
)

// VpnService is the typed v4 entry point for the "vpn" group.
// Method names follow the catalog Name field (CamelCased); the
// underlying HTTP verb and path are documented above each method.
type VpnService struct {
	client *ikuaiapi.Client
}

// PathVpn is the v4 catalog table for this group; it is exported so
// callers can iterate endpoints or build dynamic requests.
var PathVpn = pathGroupVpn()

func pathGroupVpn() []V4Endpoint {
	src := ikuaiapi.V4EndpointCatalog
	out := make([]V4Endpoint, 0, 16)
	for _, ep := range src {
		if ep.Group == "vpn" {
			out = append(out, ep)
		}
	}
	return out
}


// VpnIkev2 wraps vpn ikev2.
//
// Methods: GET, PUT
//
// Path: /vpn/ikev2
//
// Use ListVpnIkev2(ctx, opts...) for paginated reads.
// VpnIkev2ListOptions configures paginated reads of VpnIkev2.
type VpnIkev2ListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *VpnIkev2ListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListVpnIkev2 lists items at /vpn/ikev2.
func (s *VpnService) ListVpnIkev2(ctx context.Context, opts *VpnIkev2ListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/vpn/ikev2", opts.query())
}

// GetVpnIkev2 fetches one item at /vpn/ikev2.
func (s *VpnService) GetVpnIkev2(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/vpn/ikev2", q)
}

// UpdateVpnIkev2 replaces the resource at /vpn/ikev2.
func (s *VpnService) UpdateVpnIkev2(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/vpn/ikev2", body)
	return err
}


// VpnIkev2Clients wraps vpn ikev2-clients.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /vpn/ikev2/clients
//
// Use ListVpnIkev2Clients(ctx, opts...) for paginated reads.
// VpnIkev2ClientsListOptions configures paginated reads of VpnIkev2Clients.
type VpnIkev2ClientsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *VpnIkev2ClientsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListVpnIkev2Clients lists items at /vpn/ikev2/clients.
func (s *VpnService) ListVpnIkev2Clients(ctx context.Context, opts *VpnIkev2ClientsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/vpn/ikev2/clients", opts.query())
}

// GetVpnIkev2Clients fetches one item at /vpn/ikev2/clients.
func (s *VpnService) GetVpnIkev2Clients(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/vpn/ikev2/clients", q)
}

// CreateVpnIkev2Clients posts a new item to /vpn/ikev2/clients. The router returns a rowid on
// success which is propagated to the caller.
func (s *VpnService) CreateVpnIkev2Clients(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/vpn/ikev2/clients", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateVpnIkev2Clients replaces the resource at /vpn/ikev2/clients.
func (s *VpnService) UpdateVpnIkev2Clients(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/vpn/ikev2/clients", body)
	return err
}

// PatchVpnIkev2Clients partial-updates the resource at /vpn/ikev2/clients.
func (s *VpnService) PatchVpnIkev2Clients(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/vpn/ikev2/clients", body)
	return err
}

// DeleteVpnIkev2Clients removes the resource at /vpn/ikev2/clients. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteVpnIkev2ClientsWithBody to send a custom JSON body instead.
func (s *VpnService) DeleteVpnIkev2Clients(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/vpn/ikev2/clients"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteVpnIkev2ClientsWithBody removes the resource at /vpn/ikev2/clients with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteVpnIkev2Clients cannot model directly).
func (s *VpnService) DeleteVpnIkev2ClientsWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/vpn/ikev2/clients", body)
	return err
}


// VpnIpsecClients wraps vpn ipsec-clients.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /vpn/ipsec/clients
//
// Use ListVpnIpsecClients(ctx, opts...) for paginated reads.
// VpnIpsecClientsListOptions configures paginated reads of VpnIpsecClients.
type VpnIpsecClientsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *VpnIpsecClientsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListVpnIpsecClients lists items at /vpn/ipsec/clients.
func (s *VpnService) ListVpnIpsecClients(ctx context.Context, opts *VpnIpsecClientsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/vpn/ipsec/clients", opts.query())
}

// GetVpnIpsecClients fetches one item at /vpn/ipsec/clients.
func (s *VpnService) GetVpnIpsecClients(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/vpn/ipsec/clients", q)
}

// CreateVpnIpsecClients posts a new item to /vpn/ipsec/clients. The router returns a rowid on
// success which is propagated to the caller.
func (s *VpnService) CreateVpnIpsecClients(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/vpn/ipsec/clients", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateVpnIpsecClients replaces the resource at /vpn/ipsec/clients.
func (s *VpnService) UpdateVpnIpsecClients(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/vpn/ipsec/clients", body)
	return err
}

// PatchVpnIpsecClients partial-updates the resource at /vpn/ipsec/clients.
func (s *VpnService) PatchVpnIpsecClients(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/vpn/ipsec/clients", body)
	return err
}

// DeleteVpnIpsecClients removes the resource at /vpn/ipsec/clients. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteVpnIpsecClientsWithBody to send a custom JSON body instead.
func (s *VpnService) DeleteVpnIpsecClients(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/vpn/ipsec/clients"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteVpnIpsecClientsWithBody removes the resource at /vpn/ipsec/clients with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteVpnIpsecClients cannot model directly).
func (s *VpnService) DeleteVpnIpsecClientsWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/vpn/ipsec/clients", body)
	return err
}


// VpnL2Tp wraps vpn l2tp.
//
// Methods: GET, PUT
//
// Path: /vpn/l2tp
//
// Use ListVpnL2Tp(ctx, opts...) for paginated reads.
// VpnL2TpListOptions configures paginated reads of VpnL2Tp.
type VpnL2TpListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *VpnL2TpListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListVpnL2Tp lists items at /vpn/l2tp.
func (s *VpnService) ListVpnL2Tp(ctx context.Context, opts *VpnL2TpListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/vpn/l2tp", opts.query())
}

// GetVpnL2Tp fetches one item at /vpn/l2tp.
func (s *VpnService) GetVpnL2Tp(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/vpn/l2tp", q)
}

// UpdateVpnL2Tp replaces the resource at /vpn/l2tp.
func (s *VpnService) UpdateVpnL2Tp(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/vpn/l2tp", body)
	return err
}


// VpnL2TpClients wraps vpn l2tp-clients.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /vpn/l2tp/clients
//
// Use ListVpnL2TpClients(ctx, opts...) for paginated reads.
// VpnL2TpClientsListOptions configures paginated reads of VpnL2TpClients.
type VpnL2TpClientsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *VpnL2TpClientsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListVpnL2TpClients lists items at /vpn/l2tp/clients.
func (s *VpnService) ListVpnL2TpClients(ctx context.Context, opts *VpnL2TpClientsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/vpn/l2tp/clients", opts.query())
}

// GetVpnL2TpClients fetches one item at /vpn/l2tp/clients.
func (s *VpnService) GetVpnL2TpClients(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/vpn/l2tp/clients", q)
}

// CreateVpnL2TpClients posts a new item to /vpn/l2tp/clients. The router returns a rowid on
// success which is propagated to the caller.
func (s *VpnService) CreateVpnL2TpClients(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/vpn/l2tp/clients", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateVpnL2TpClients replaces the resource at /vpn/l2tp/clients.
func (s *VpnService) UpdateVpnL2TpClients(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/vpn/l2tp/clients", body)
	return err
}

// PatchVpnL2TpClients partial-updates the resource at /vpn/l2tp/clients.
func (s *VpnService) PatchVpnL2TpClients(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/vpn/l2tp/clients", body)
	return err
}

// DeleteVpnL2TpClients removes the resource at /vpn/l2tp/clients. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteVpnL2TpClientsWithBody to send a custom JSON body instead.
func (s *VpnService) DeleteVpnL2TpClients(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/vpn/l2tp/clients"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteVpnL2TpClientsWithBody removes the resource at /vpn/l2tp/clients with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteVpnL2TpClients cannot model directly).
func (s *VpnService) DeleteVpnL2TpClientsWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/vpn/l2tp/clients", body)
	return err
}


// VpnOpenvpn wraps vpn openvpn.
//
// Methods: GET, PUT
//
// Path: /vpn/openvpn
//
// Use ListVpnOpenvpn(ctx, opts...) for paginated reads.
// VpnOpenvpnListOptions configures paginated reads of VpnOpenvpn.
type VpnOpenvpnListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *VpnOpenvpnListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListVpnOpenvpn lists items at /vpn/openvpn.
func (s *VpnService) ListVpnOpenvpn(ctx context.Context, opts *VpnOpenvpnListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/vpn/openvpn", opts.query())
}

// GetVpnOpenvpn fetches one item at /vpn/openvpn.
func (s *VpnService) GetVpnOpenvpn(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/vpn/openvpn", q)
}

// UpdateVpnOpenvpn replaces the resource at /vpn/openvpn.
func (s *VpnService) UpdateVpnOpenvpn(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/vpn/openvpn", body)
	return err
}


// VpnOpenvpnClients wraps vpn openvpn-clients.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /vpn/openvpn/clients
//
// Use ListVpnOpenvpnClients(ctx, opts...) for paginated reads.
// VpnOpenvpnClientsListOptions configures paginated reads of VpnOpenvpnClients.
type VpnOpenvpnClientsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *VpnOpenvpnClientsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListVpnOpenvpnClients lists items at /vpn/openvpn/clients.
func (s *VpnService) ListVpnOpenvpnClients(ctx context.Context, opts *VpnOpenvpnClientsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/vpn/openvpn/clients", opts.query())
}

// GetVpnOpenvpnClients fetches one item at /vpn/openvpn/clients.
func (s *VpnService) GetVpnOpenvpnClients(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/vpn/openvpn/clients", q)
}

// CreateVpnOpenvpnClients posts a new item to /vpn/openvpn/clients. The router returns a rowid on
// success which is propagated to the caller.
func (s *VpnService) CreateVpnOpenvpnClients(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/vpn/openvpn/clients", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateVpnOpenvpnClients replaces the resource at /vpn/openvpn/clients.
func (s *VpnService) UpdateVpnOpenvpnClients(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/vpn/openvpn/clients", body)
	return err
}

// PatchVpnOpenvpnClients partial-updates the resource at /vpn/openvpn/clients.
func (s *VpnService) PatchVpnOpenvpnClients(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/vpn/openvpn/clients", body)
	return err
}

// DeleteVpnOpenvpnClients removes the resource at /vpn/openvpn/clients. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteVpnOpenvpnClientsWithBody to send a custom JSON body instead.
func (s *VpnService) DeleteVpnOpenvpnClients(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/vpn/openvpn/clients"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteVpnOpenvpnClientsWithBody removes the resource at /vpn/openvpn/clients with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteVpnOpenvpnClients cannot model directly).
func (s *VpnService) DeleteVpnOpenvpnClientsWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/vpn/openvpn/clients", body)
	return err
}


// VpnPptp wraps vpn pptp.
//
// Methods: GET, PUT
//
// Path: /vpn/pptp
//
// Use ListVpnPptp(ctx, opts...) for paginated reads.
// VpnPptpListOptions configures paginated reads of VpnPptp.
type VpnPptpListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *VpnPptpListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListVpnPptp lists items at /vpn/pptp.
func (s *VpnService) ListVpnPptp(ctx context.Context, opts *VpnPptpListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/vpn/pptp", opts.query())
}

// GetVpnPptp fetches one item at /vpn/pptp.
func (s *VpnService) GetVpnPptp(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/vpn/pptp", q)
}

// UpdateVpnPptp replaces the resource at /vpn/pptp.
func (s *VpnService) UpdateVpnPptp(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/vpn/pptp", body)
	return err
}


// VpnPptpClients wraps vpn pptp-clients.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /vpn/pptp/clients
//
// Use ListVpnPptpClients(ctx, opts...) for paginated reads.
// VpnPptpClientsListOptions configures paginated reads of VpnPptpClients.
type VpnPptpClientsListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *VpnPptpClientsListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListVpnPptpClients lists items at /vpn/pptp/clients.
func (s *VpnService) ListVpnPptpClients(ctx context.Context, opts *VpnPptpClientsListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/vpn/pptp/clients", opts.query())
}

// GetVpnPptpClients fetches one item at /vpn/pptp/clients.
func (s *VpnService) GetVpnPptpClients(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/vpn/pptp/clients", q)
}

// CreateVpnPptpClients posts a new item to /vpn/pptp/clients. The router returns a rowid on
// success which is propagated to the caller.
func (s *VpnService) CreateVpnPptpClients(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/vpn/pptp/clients", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateVpnPptpClients replaces the resource at /vpn/pptp/clients.
func (s *VpnService) UpdateVpnPptpClients(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/vpn/pptp/clients", body)
	return err
}

// PatchVpnPptpClients partial-updates the resource at /vpn/pptp/clients.
func (s *VpnService) PatchVpnPptpClients(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/vpn/pptp/clients", body)
	return err
}

// DeleteVpnPptpClients removes the resource at /vpn/pptp/clients. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteVpnPptpClientsWithBody to send a custom JSON body instead.
func (s *VpnService) DeleteVpnPptpClients(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/vpn/pptp/clients"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteVpnPptpClientsWithBody removes the resource at /vpn/pptp/clients with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteVpnPptpClients cannot model directly).
func (s *VpnService) DeleteVpnPptpClientsWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/vpn/pptp/clients", body)
	return err
}


// VpnWireguard wraps vpn wireguard.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /vpn/wireguard
//
// Use ListVpnWireguard(ctx, opts...) for paginated reads.
// VpnWireguardListOptions configures paginated reads of VpnWireguard.
type VpnWireguardListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *VpnWireguardListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListVpnWireguard lists items at /vpn/wireguard.
func (s *VpnService) ListVpnWireguard(ctx context.Context, opts *VpnWireguardListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/vpn/wireguard", opts.query())
}

// GetVpnWireguard fetches one item at /vpn/wireguard.
func (s *VpnService) GetVpnWireguard(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/vpn/wireguard", q)
}

// CreateVpnWireguard posts a new item to /vpn/wireguard. The router returns a rowid on
// success which is propagated to the caller.
func (s *VpnService) CreateVpnWireguard(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/vpn/wireguard", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateVpnWireguard replaces the resource at /vpn/wireguard.
func (s *VpnService) UpdateVpnWireguard(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/vpn/wireguard", body)
	return err
}

// PatchVpnWireguard partial-updates the resource at /vpn/wireguard.
func (s *VpnService) PatchVpnWireguard(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/vpn/wireguard", body)
	return err
}

// DeleteVpnWireguard removes the resource at /vpn/wireguard. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteVpnWireguardWithBody to send a custom JSON body instead.
func (s *VpnService) DeleteVpnWireguard(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/vpn/wireguard"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteVpnWireguardWithBody removes the resource at /vpn/wireguard with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteVpnWireguard cannot model directly).
func (s *VpnService) DeleteVpnWireguardWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/vpn/wireguard", body)
	return err
}


// Field hints for this group (iKuai firmware field names):
//   name             Tunnel name
//   server_ip        VPN server IP (PPTP / L2TP / OpenVPN server)
//   username         VPN account username
//   password         VPN account password
//   enabled          yes | no
