// Code generated by ikuai-api/codegen. DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	ikuaiapi "github.com/zy84338719/ikuai-api"
	"strconv"
)

// WirelessService is the typed v4 entry point for the "wireless" group.
// Method names follow the catalog Name field (CamelCased); the
// underlying HTTP verb and path are documented above each method.
type WirelessService struct {
	client *ikuaiapi.Client
}

// PathWireless is the v4 catalog table for this group; it is exported so
// callers can iterate endpoints or build dynamic requests.
var PathWireless = pathGroupWireless()

func pathGroupWireless() []V4Endpoint {
	src := ikuaiapi.V4EndpointCatalog
	out := make([]V4Endpoint, 0, 16)
	for _, ep := range src {
		if ep.Group == "wireless" {
			out = append(out, ep)
		}
	}
	return out
}

// WirelessAccessControlRules wraps wireless access-control-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /wireless/access-control/rules
//
// Use ListWirelessAccessControlRules(ctx, opts...) for paginated reads.
// WirelessAccessControlRulesListOptions configures paginated reads of WirelessAccessControlRules.
type WirelessAccessControlRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *WirelessAccessControlRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListWirelessAccessControlRules lists items at /wireless/access-control/rules.
func (s *WirelessService) ListWirelessAccessControlRules(ctx context.Context, opts *WirelessAccessControlRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/wireless/access-control/rules", opts.query())
}

// GetWirelessAccessControlRules fetches one item at /wireless/access-control/rules.
func (s *WirelessService) GetWirelessAccessControlRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/wireless/access-control/rules", q)
}

// CreateWirelessAccessControlRules posts a new item to /wireless/access-control/rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *WirelessService) CreateWirelessAccessControlRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/wireless/access-control/rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateWirelessAccessControlRules replaces the resource at /wireless/access-control/rules.
func (s *WirelessService) UpdateWirelessAccessControlRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/wireless/access-control/rules", body)
	return err
}

// PatchWirelessAccessControlRules partial-updates the resource at /wireless/access-control/rules.
func (s *WirelessService) PatchWirelessAccessControlRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/wireless/access-control/rules", body)
	return err
}

// DeleteWirelessAccessControlRules removes the resource at /wireless/access-control/rules. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteWirelessAccessControlRulesWithBody to send a custom JSON body instead.
func (s *WirelessService) DeleteWirelessAccessControlRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/wireless/access-control/rules"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteWirelessAccessControlRulesWithBody removes the resource at /wireless/access-control/rules with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteWirelessAccessControlRules cannot model directly).
func (s *WirelessService) DeleteWirelessAccessControlRulesWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/wireless/access-control/rules", body)
	return err
}

// WirelessVlanRules wraps wireless vlan-rules.
//
// Methods: GET, POST, PUT, PATCH, DELETE
//
// Path: /wireless/vlan/rules
//
// Use ListWirelessVlanRules(ctx, opts...) for paginated reads.
// WirelessVlanRulesListOptions configures paginated reads of WirelessVlanRules.
type WirelessVlanRulesListOptions struct {
	Page     int
	PageSize int
	Filter   string
	Order    string
	OrderBy  string
}

func (o *WirelessVlanRulesListOptions) query() map[string]string {
	if o == nil {
		return nil
	}
	q := map[string]string{
		"page":      strconv.Itoa(o.Page),
		"page_size": strconv.Itoa(o.PageSize),
	}
	if o.Filter != "" {
		q["filter"] = o.Filter
	}
	if o.Order != "" {
		q["order"] = o.Order
	}
	if o.OrderBy != "" {
		q["order_by"] = o.OrderBy
	}
	return q
}

// ListWirelessVlanRules lists items at /wireless/vlan/rules.
func (s *WirelessService) ListWirelessVlanRules(ctx context.Context, opts *WirelessVlanRulesListOptions) (json.RawMessage, error) {
	return s.client.Get(ctx, "/wireless/vlan/rules", opts.query())
}

// GetWirelessVlanRules fetches one item at /wireless/vlan/rules.
func (s *WirelessService) GetWirelessVlanRules(ctx context.Context, id int64) (json.RawMessage, error) {
	q := map[string]string{"id": strconv.FormatInt(id, 10)}
	return s.client.Get(ctx, "/wireless/vlan/rules", q)
}

// CreateWirelessVlanRules posts a new item to /wireless/vlan/rules. The router returns a rowid on
// success which is propagated to the caller.
func (s *WirelessService) CreateWirelessVlanRules(ctx context.Context, body any) (int64, error) {
	raw, err := s.client.Post(ctx, "/wireless/vlan/rules", body)
	if err != nil {
		return 0, err
	}
	return extractRowID(raw)
}

// UpdateWirelessVlanRules replaces the resource at /wireless/vlan/rules.
func (s *WirelessService) UpdateWirelessVlanRules(ctx context.Context, body any) error {
	_, err := s.client.Put(ctx, "/wireless/vlan/rules", body)
	return err
}

// PatchWirelessVlanRules partial-updates the resource at /wireless/vlan/rules.
func (s *WirelessService) PatchWirelessVlanRules(ctx context.Context, body any) error {
	_, err := s.client.Patch(ctx, "/wireless/vlan/rules", body)
	return err
}

// DeleteWirelessVlanRules removes the resource at /wireless/vlan/rules. iKuai expects the
// resource identifier as the ?id= query parameter, not in the JSON
// body. Pass DeleteWirelessVlanRulesWithBody to send a custom JSON body instead.
func (s *WirelessService) DeleteWirelessVlanRules(ctx context.Context, id int64) error {
	_, err := s.client.Delete(ctx, "/wireless/vlan/rules"+"?id="+strconv.FormatInt(id, 10), nil)
	return err
}

// DeleteWirelessVlanRulesWithBody removes the resource at /wireless/vlan/rules with a custom
// JSON body. iKuai also accepts a few DELETE requests that carry
// parameters in the body (e.g. /system/backup?srcfile=… which the
// wrapper DeleteWirelessVlanRules cannot model directly).
func (s *WirelessService) DeleteWirelessVlanRulesWithBody(ctx context.Context, body any) error {
	_, err := s.client.Delete(ctx, "/wireless/vlan/rules", body)
	return err
}
